using System.Text;
using ServerManager.Contracts;

namespace ServerManager.Infrastructure.Games.Minecraft;

public static class MinecraftPropertiesSerializer
{
    private static readonly HashSet<string> Difficulties =
        new(StringComparer.OrdinalIgnoreCase) { "peaceful", "easy", "normal", "hard" };

    private static readonly HashSet<string> GameModes =
        new(StringComparer.OrdinalIgnoreCase) { "survival", "creative", "adventure", "spectator" };

    public static string Serialize(MinecraftServerSettings settings, int port)
    {
        Validate(settings, port);
        var values = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["difficulty"] = settings.Difficulty.ToLowerInvariant(),
            ["enable-command-block"] = "false",
            ["enforce-whitelist"] = settings.WhitelistEnabled.ToString().ToLowerInvariant(),
            ["gamemode"] = settings.GameMode.ToLowerInvariant(),
            ["hardcore"] = settings.Hardcore.ToString().ToLowerInvariant(),
            ["max-players"] = settings.MaxPlayers.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["motd"] = Escape(settings.Motd),
            ["online-mode"] = settings.OnlineMode.ToString().ToLowerInvariant(),
            ["pvp"] = settings.Pvp.ToString().ToLowerInvariant(),
            ["server-port"] = port.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["simulation-distance"] =
                settings.SimulationDistance.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["view-distance"] =
                settings.ViewDistance.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["white-list"] = settings.WhitelistEnabled.ToString().ToLowerInvariant()
        };

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by 1Salem Server Manager");
        foreach (var (key, value) in values)
        {
            builder.Append(key).Append('=').AppendLine(value);
        }

        return builder.ToString();
    }

    public static IReadOnlyDictionary<string, string> Parse(string content)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        using var reader = new StringReader(content);
        while (reader.ReadLine() is { } line)
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed[0] is '#' or '!')
            {
                continue;
            }

            var separator = FindSeparator(trimmed);
            if (separator <= 0)
            {
                continue;
            }

            values[trimmed[..separator].Trim()] = Unescape(trimmed[(separator + 1)..].Trim());
        }

        return values;
    }

    public static string Merge(
        string existingContent,
        MinecraftServerSettings settings,
        int port)
    {
        var generated = Serialize(settings, port);
        var managedLines = generated
            .Split(
                ['\r', '\n'],
                StringSplitOptions.RemoveEmptyEntries)
            .Where(line => !line.StartsWith('#'))
            .ToDictionary(
                line => line[..line.IndexOf('=')],
                line => line,
                StringComparer.OrdinalIgnoreCase);
        var output = new List<string>();
        var written = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var line in existingContent.Split('\n'))
        {
            var normalized = line.TrimEnd('\r');
            var separator = FindSeparator(normalized);
            var key = separator > 0
                ? normalized[..separator].Trim()
                : string.Empty;
            if (managedLines.TryGetValue(key, out var replacement))
            {
                if (written.Add(key))
                {
                    output.Add(replacement);
                }

                continue;
            }

            output.Add(normalized);
        }

        foreach (var (key, line) in managedLines)
        {
            if (written.Add(key))
            {
                output.Add(line);
            }
        }

        return string.Join(Environment.NewLine, output).TrimEnd() +
               Environment.NewLine;
    }

    private static void Validate(MinecraftServerSettings settings, int port)
    {
        ArgumentNullException.ThrowIfNull(settings);
        if (port is < 1 or > 65_535)
        {
            throw new ArgumentOutOfRangeException(nameof(port));
        }

        if (settings.MaxPlayers is < 1 or > 1_000)
        {
            throw new ArgumentOutOfRangeException(nameof(settings), "Max players must be between 1 and 1000.");
        }

        if (!Difficulties.Contains(settings.Difficulty))
        {
            throw new ArgumentException("Unsupported Minecraft difficulty.", nameof(settings));
        }

        if (!GameModes.Contains(settings.GameMode))
        {
            throw new ArgumentException("Unsupported Minecraft game mode.", nameof(settings));
        }

        if (settings.ViewDistance is < 2 or > 32 ||
            settings.SimulationDistance is < 2 or > 32)
        {
            throw new ArgumentOutOfRangeException(
                nameof(settings),
                "View and simulation distances must be between 2 and 32.");
        }
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\r", string.Empty, StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("=", "\\=", StringComparison.Ordinal)
            .Replace(":", "\\:", StringComparison.Ordinal);

    private static string Unescape(string value) =>
        value.Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\:", ":", StringComparison.Ordinal)
            .Replace("\\=", "=", StringComparison.Ordinal)
            .Replace("\\\\", "\\", StringComparison.Ordinal);

    private static int FindSeparator(string line)
    {
        var escaped = false;
        for (var index = 0; index < line.Length; index++)
        {
            if (line[index] == '\\')
            {
                escaped = !escaped;
                continue;
            }

            if (!escaped && line[index] is '=' or ':')
            {
                return index;
            }

            escaped = false;
        }

        return -1;
    }
}
