using System.Text;
using ServerManager.Contracts;

namespace ServerManager.Infrastructure.Games.Minecraft;

public static class MinecraftPropertiesSerializer
{
    public static IReadOnlySet<string> ManagedKeys { get; } =
        new HashSet<string>(
            [
                "allow-flight",
                "difficulty",
                "enable-command-block",
                "enforce-whitelist",
                "gamemode",
                "generate-structures",
                "hardcore",
                "level-name",
                "level-seed",
                "level-type",
                "max-players",
                "motd",
                "online-mode",
                "pvp",
                "server-port",
                "simulation-distance",
                "spawn-animals",
                "spawn-monsters",
                "spawn-npcs",
                "spawn-protection",
                "view-distance",
                "white-list"
            ],
            StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Reads server.properties while Minecraft may have it open: Paper and Purpur 26.x keep it open
    /// for writing while they run, so File.ReadAllText (which refuses other writers) fails. Only reads.
    /// </summary>
    public static string ReadFile(string path)
    {
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
        return reader.ReadToEnd();
    }

    private static readonly HashSet<string> Difficulties =
        new(StringComparer.OrdinalIgnoreCase) { "peaceful", "easy", "normal", "hard" };

    private static readonly HashSet<string> GameModes =
        new(StringComparer.OrdinalIgnoreCase) { "survival", "creative", "adventure", "spectator" };

    public static string Serialize(MinecraftServerSettings settings, int port)
    {
        Validate(settings, port);
        var values = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["difficulty"] = settings.Difficulty.ToLowerInvariant(),
            ["allow-flight"] = settings.AllowFlight.ToString().ToLowerInvariant(),
            ["enable-command-block"] = settings.EnableCommandBlocks.ToString().ToLowerInvariant(),
            ["enforce-whitelist"] = settings.WhitelistEnabled.ToString().ToLowerInvariant(),
            ["generate-structures"] = settings.GenerateStructures.ToString().ToLowerInvariant(),
            ["gamemode"] = settings.GameMode.ToLowerInvariant(),
            ["hardcore"] = settings.Hardcore.ToString().ToLowerInvariant(),
            ["level-name"] = Escape(settings.LevelName),
            ["level-seed"] = Escape(settings.LevelSeed),
            ["level-type"] = settings.LevelType,
            ["max-players"] = settings.MaxPlayers.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["motd"] = Escape(settings.Motd),
            ["online-mode"] = settings.OnlineMode.ToString().ToLowerInvariant(),
            ["pvp"] = settings.Pvp.ToString().ToLowerInvariant(),
            ["server-port"] = port.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["spawn-animals"] = settings.SpawnAnimals.ToString().ToLowerInvariant(),
            ["spawn-monsters"] = settings.SpawnMonsters.ToString().ToLowerInvariant(),
            ["spawn-npcs"] = settings.SpawnNpcs.ToString().ToLowerInvariant(),
            ["spawn-protection"] =
                settings.SpawnProtection.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["simulation-distance"] =
                settings.SimulationDistance.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["view-distance"] =
                settings.ViewDistance.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["white-list"] = settings.WhitelistEnabled.ToString().ToLowerInvariant()
        };

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by 1Salem Server Manager");
        foreach (var (key, value) in values)
        {
            builder.Append(key).Append('=').AppendLine(value);
        }

        return builder.ToString();
    }

    public static IReadOnlyDictionary<string, string> Parse(string content)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        using var reader = new StringReader(content);
        while (reader.ReadLine() is { } line)
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed[0] is '#' or '!')
            {
                continue;
            }

            var separator = FindSeparator(trimmed);
            if (separator <= 0)
            {
                continue;
            }

            values[trimmed[..separator].Trim()] = Unescape(trimmed[(separator + 1)..].Trim());
        }

        return values;
    }

    public static string Merge(
        string existingContent,
        MinecraftServerSettings settings,
        int port)
    {
        var generated = Serialize(settings, port);
        var managedLines = generated
            .Split(
                ['\r', '\n'],
                StringSplitOptions.RemoveEmptyEntries)
            .Where(line => !line.StartsWith('#'))
            .ToDictionary(
                line => line[..line.IndexOf('=')],
                line => line,
                StringComparer.OrdinalIgnoreCase);
        var output = new List<string>();
        var written = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var line in existingContent.Split('\n'))
        {
            var normalized = line.TrimEnd('\r');
            var separator = FindSeparator(normalized);
            var key = separator > 0
                ? normalized[..separator].Trim()
                : string.Empty;
            if (managedLines.TryGetValue(key, out var replacement))
            {
                if (written.Add(key))
                {
                    output.Add(replacement);
                }

                continue;
            }

            output.Add(normalized);
        }

        foreach (var (key, line) in managedLines)
        {
            if (written.Add(key))
            {
                output.Add(line);
            }
        }

        return string.Join(Environment.NewLine, output).TrimEnd() +
               Environment.NewLine;
    }

    /// <summary>
    /// Sets only the given keys: the first occurrence of each is replaced where it stands,
    /// missing ones are appended, and every other line (unknown keys, comments, order) is kept.
    /// Setting "white-list" also sets "enforce-whitelist", as the settings editor always has.
    /// </summary>
    public static string SetValues(string existingContent, IReadOnlyDictionary<string, string> values)
    {
        ArgumentNullException.ThrowIfNull(existingContent);
        ArgumentNullException.ThrowIfNull(values);
        var wanted = new Dictionary<string, string>(values, StringComparer.OrdinalIgnoreCase);
        if (wanted.TryGetValue("white-list", out var whitelist))
        {
            wanted["enforce-whitelist"] = whitelist;
        }

        var output = new List<string>();
        var written = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var line in existingContent.Split('\n'))
        {
            var normalized = line.TrimEnd('\r');
            var separator = FindSeparator(normalized);
            var key = separator > 0 && !normalized.TrimStart().StartsWith('#') && !normalized.TrimStart().StartsWith('!')
                ? normalized[..separator].Trim()
                : string.Empty;
            if (key.Length > 0 && wanted.TryGetValue(key, out var value))
            {
                if (written.Add(key))
                {
                    output.Add($"{key}={Escape(value)}");
                }

                continue;
            }

            output.Add(normalized);
        }

        foreach (var (key, value) in wanted)
        {
            if (written.Add(key))
            {
                output.Add($"{key}={Escape(value)}");
            }
        }

        return string.Join(Environment.NewLine, output).TrimEnd() + Environment.NewLine;
    }

    private static void Validate(MinecraftServerSettings settings, int port)
    {
        ArgumentNullException.ThrowIfNull(settings);
        if (port is < 1 or > 65_535)
        {
            throw new ArgumentOutOfRangeException(nameof(port));
        }

        if (settings.MaxPlayers is < 1 or > 1_000)
        {
            throw new ArgumentOutOfRangeException(nameof(settings), "Max players must be between 1 and 1000.");
        }

        if (!Difficulties.Contains(settings.Difficulty))
        {
            throw new ArgumentException("Unsupported Minecraft difficulty.", nameof(settings));
        }

        if (!GameModes.Contains(settings.GameMode))
        {
            throw new ArgumentException("Unsupported Minecraft game mode.", nameof(settings));
        }

        if (settings.ViewDistance is < 2 or > 32 ||
            settings.SimulationDistance is < 2 or > 32)
        {
            throw new ArgumentOutOfRangeException(
                nameof(settings),
                "View and simulation distances must be between 2 and 32.");
        }

        if (settings.SpawnProtection is < 0 or > 64)
        {
            throw new ArgumentOutOfRangeException(
                nameof(settings),
                "Spawn protection must be between 0 and 64.");
        }

        if (string.IsNullOrWhiteSpace(settings.LevelName) ||
            settings.LevelName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
        {
            throw new ArgumentException(
                "The Minecraft level name is invalid.",
                nameof(settings));
        }

        if (string.IsNullOrWhiteSpace(settings.LevelType))
        {
            throw new ArgumentException(
                "The Minecraft world type is required.",
                nameof(settings));
        }
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\r", string.Empty, StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("=", "\\=", StringComparison.Ordinal)
            .Replace(":", "\\:", StringComparison.Ordinal);

    private static string Unescape(string value) =>
        value.Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\:", ":", StringComparison.Ordinal)
            .Replace("\\=", "=", StringComparison.Ordinal)
            .Replace("\\\\", "\\", StringComparison.Ordinal);

    private static int FindSeparator(string line)
    {
        var escaped = false;
        for (var index = 0; index < line.Length; index++)
        {
            if (line[index] == '\\')
            {
                escaped = !escaped;
                continue;
            }

            if (!escaped && line[index] is '=' or ':')
            {
                return index;
            }

            escaped = false;
        }

        return -1;
    }
}
