using System.Globalization;
using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Media;
using Microsoft.Win32;

namespace ServerManager.Client.Shell;

public enum AppTheme
{
    Dark = 0,
    Light = 1,
    FollowWindows = 2
}

/// <summary>
/// Persisted UI preferences. <paramref name="SidebarCollapsed"/> is optional so an older
/// preferences file written before Build 6 still deserializes, defaulting to the expanded
/// sidebar rather than silently collapsing it.
/// </summary>
public sealed record UiPreferences(
    string Language,
    AppTheme Theme,
    bool SidebarCollapsed = false)
{
    public static UiPreferences Default { get; } = new("en-US", AppTheme.Dark, false);
}

public sealed class UiPreferencesStore
{
    private static readonly JsonSerializerOptions SerializerOptions =
        new(JsonSerializerDefaults.Web) { WriteIndented = true };
    private readonly string _path;

    public UiPreferencesStore()
        : this(Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "1SalemServerManager",
            "ui-preferences.json"))
    {
    }

    internal UiPreferencesStore(string path) => _path = Path.GetFullPath(path);

    public UiPreferences Load()
    {
        try
        {
            return File.Exists(_path)
                ? JsonSerializer.Deserialize<UiPreferences>(
                    File.ReadAllText(_path),
                    SerializerOptions) ?? UiPreferences.Default
                : UiPreferences.Default;
        }
        catch (JsonException)
        {
            return UiPreferences.Default;
        }
    }

    public void Save(UiPreferences preferences)
    {
        ArgumentNullException.ThrowIfNull(preferences);
        _ = CultureInfo.GetCultureInfo(preferences.Language);
        Directory.CreateDirectory(Path.GetDirectoryName(_path)!);
        var temporaryPath = _path + ".new";
        File.WriteAllText(
            temporaryPath,
            JsonSerializer.Serialize(preferences, SerializerOptions));
        File.Move(temporaryPath, _path, true);
    }
}

public static class ThemeService
{
    private static readonly IReadOnlyDictionary<string, string> DarkColors =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBrush"] = "#08131F",
            ["PanelBrush"] = "#0E1C2B",
            ["PanelAltBrush"] = "#16283A",
            ["AccentBrush"] = "#2CB8B3",
            ["SuccessBrush"] = "#43B581",
            ["WarningBrush"] = "#E0A83B",
            ["DangerBrush"] = "#D85B63",
            ["DisabledBrush"] = "#405064",
            ["TextBrush"] = "#F1F6FA",
            ["MutedTextBrush"] = "#9FB0C2",
            ["ControlSurfaceBrush"] = "#102235",
            ["ControlHoverBrush"] = "#193149",
            ["ControlBorderBrush"] = "#3B566D",
            ["FocusBrush"] = "#72E2DE",
            ["SelectionBrush"] = "#087F7B",
            ["TabBrush"] = "#16283A",
            ["TabDisabledBrush"] = "#202F40",
            ["DangerSurfaceBrush"] = "#351D27",

            // Build 6 design-system tokens. Every semantic token the new UI binds to must
            // appear in both tables, otherwise it keeps its App.xaml literal and stops
            // following the theme.
            ["SurfaceBrush"] = "#08131F",
            ["SurfaceRaisedBrush"] = "#101F2E",
            ["SurfaceOverlayBrush"] = "#16283A",
            ["SurfaceSunkenBrush"] = "#050D16",
            ["SidebarBrush"] = "#0A1622",
            ["TextPrimaryBrush"] = "#F1F6FA",
            ["TextSecondaryBrush"] = "#9FB0C2",
            // Measured 4.12:1 on SurfaceRaised at #6C8099, under the 4.5:1 AA floor. This
            // carries the public address players have to read, so it is now 5.1:1.
            ["TextTertiaryBrush"] = "#7D91A8",
            ["BorderSubtleBrush"] = "#1E3448",
            ["BorderStrongBrush"] = "#2C4459",
            ["AccentSoftBrush"] = "#123B3E",
            ["SuccessSoftBrush"] = "#12312A",
            ["WarningSoftBrush"] = "#33290F",
            ["DangerSoftBrush"] = "#351D27"
        };

    private static readonly IReadOnlyDictionary<string, string> LightColors =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBrush"] = "#F4F6F9",
            ["PanelBrush"] = "#FFFFFF",
            ["PanelAltBrush"] = "#E5EAF1",
            ["AccentBrush"] = "#087F7B",
            ["SuccessBrush"] = "#188454",
            ["WarningBrush"] = "#A96F00",
            ["DangerBrush"] = "#B62D3A",
            ["DisabledBrush"] = "#C7D0DB",
            ["TextBrush"] = "#16202D",
            ["MutedTextBrush"] = "#526173",
            ["ControlSurfaceBrush"] = "#FFFFFF",
            ["ControlHoverBrush"] = "#EDF2F7",
            ["ControlBorderBrush"] = "#91A0B3",
            ["FocusBrush"] = "#087F7B",
            ["SelectionBrush"] = "#087F7B",
            ["TabBrush"] = "#E5EAF1",
            ["TabDisabledBrush"] = "#DCE2EA",
            ["DangerSurfaceBrush"] = "#FBEAEC",

            ["SurfaceBrush"] = "#F4F6F9",
            ["SurfaceRaisedBrush"] = "#FFFFFF",
            ["SurfaceOverlayBrush"] = "#EDF2F7",
            ["SurfaceSunkenBrush"] = "#E8EDF3",
            ["SidebarBrush"] = "#FFFFFF",
            ["TextPrimaryBrush"] = "#16202D",
            ["TextSecondaryBrush"] = "#526173",
            // 4.30:1 on white at #6D7C8D, also under AA; darkened to 5.35:1.
            ["TextTertiaryBrush"] = "#5F6E7F",
            ["BorderSubtleBrush"] = "#D8E0E9",
            ["BorderStrongBrush"] = "#B9C5D3",
            ["AccentSoftBrush"] = "#DCF0EF",
            ["SuccessSoftBrush"] = "#DFF1E7",
            ["WarningSoftBrush"] = "#FBEFD8",
            ["DangerSoftBrush"] = "#FBEAEC"
        };

    private static AppTheme _requestedTheme = AppTheme.Dark;
    private static bool _listeningForWindowsChanges;

    /// <summary>
    /// Raised after the palette changes. Brushes declared in XAML are frozen, so applying a
    /// theme <i>replaces</i> the resource rather than recolouring it. DynamicResource consumers
    /// follow that automatically, but anything that resolved a brush in code — a converter, or
    /// a page assigning Fill directly — is still holding the previous theme's object and must
    /// re-resolve here.
    /// </summary>
    public static event EventHandler? ThemeChanged;

    public static void Apply(AppTheme theme)
    {
        // The event fires on every path: the requested theme has changed even when there is
        // no Application to recolour, and listeners should not have to care which case ran.
        try
        {
            ApplyCore(theme);
        }
        finally
        {
            ThemeChanged?.Invoke(null, EventArgs.Empty);
        }
    }

    private static void ApplyCore(AppTheme theme)
    {
        _requestedTheme = theme;
        EnsureWindowsThemeListener();
        var application = System.Windows.Application.Current;
        if (application is null)
        {
            return;
        }

        if (SystemParameters.HighContrast)
        {
            application.Resources["WindowBrush"] = System.Windows.SystemColors.WindowBrush;
            application.Resources["PanelBrush"] = System.Windows.SystemColors.ControlBrush;
            application.Resources["PanelAltBrush"] = System.Windows.SystemColors.ControlLightBrush;
            application.Resources["AccentBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["SuccessBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["WarningBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["DangerBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["DisabledBrush"] = System.Windows.SystemColors.GrayTextBrush;
            application.Resources["TextBrush"] = System.Windows.SystemColors.WindowTextBrush;
            application.Resources["MutedTextBrush"] = System.Windows.SystemColors.GrayTextBrush;
            application.Resources["ControlSurfaceBrush"] = System.Windows.SystemColors.WindowBrush;
            application.Resources["ControlHoverBrush"] = System.Windows.SystemColors.ControlLightBrush;
            application.Resources["ControlBorderBrush"] = System.Windows.SystemColors.WindowTextBrush;
            application.Resources["FocusBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["SelectionBrush"] = System.Windows.SystemColors.HighlightBrush;
            application.Resources["TabBrush"] = System.Windows.SystemColors.ControlBrush;
            application.Resources["TabDisabledBrush"] = System.Windows.SystemColors.ControlDarkBrush;
            application.Resources["DangerSurfaceBrush"] = System.Windows.SystemColors.ControlBrush;
            return;
        }

        var effectiveTheme = theme == AppTheme.FollowWindows
            ? ReadWindowsTheme()
            : theme;
        var colors = effectiveTheme == AppTheme.Light ? LightColors : DarkColors;
        foreach (var (key, value) in colors)
        {
            if (application.Resources[key] is SolidColorBrush existing &&
                !existing.IsFrozen)
            {
                existing.Color = (System.Windows.Media.Color)
                    System.Windows.Media.ColorConverter.ConvertFromString(value);
            }
            else
            {
                application.Resources[key] =
                    new SolidColorBrush(
                        (System.Windows.Media.Color)
                        System.Windows.Media.ColorConverter.ConvertFromString(value));
            }
        }
    }

    internal static AppTheme ReadWindowsTheme()
    {
        try
        {
            var value = Registry.GetValue(
                @"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize",
                "AppsUseLightTheme",
                0);
            return Convert.ToInt32(value, CultureInfo.InvariantCulture) == 1
                ? AppTheme.Light
                : AppTheme.Dark;
        }
        catch (Exception exception) when (
            exception is IOException or UnauthorizedAccessException or
            System.Security.SecurityException or FormatException or
            InvalidCastException)
        {
            return AppTheme.Dark;
        }
    }

    private static void EnsureWindowsThemeListener()
    {
        if (_listeningForWindowsChanges)
        {
            return;
        }

        SystemEvents.UserPreferenceChanged += OnUserPreferenceChanged;
        _listeningForWindowsChanges = true;
    }

    private static void OnUserPreferenceChanged(
        object sender,
        UserPreferenceChangedEventArgs eventArgs)
    {
        if (_requestedTheme != AppTheme.FollowWindows ||
            eventArgs.Category is not (
                UserPreferenceCategory.Color or
                UserPreferenceCategory.General or
                UserPreferenceCategory.VisualStyle))
        {
            return;
        }

        var dispatcher = System.Windows.Application.Current?.Dispatcher;
        if (dispatcher is not null)
        {
            _ = dispatcher.BeginInvoke(() => Apply(AppTheme.FollowWindows));
        }
    }
}

public static class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppTitle"] = "1Salem Server Manager",
            ["DashboardSubtitle"] = "Native server dashboard",
            ["AgentConnection"] = "Agent connection",
            ["Refresh"] = "Refresh",
            ["AgentPc"] = "Agent PC",
            ["AgentVersion"] = "Agent version",
            ["Database"] = "Database",
            ["FoundationTitle"] = "Server management foundation",
            ["FoundationDescription"] = "Local process control, verified backups, game installers, and resource safeguards are available from their sections.",
            ["Footer"] = "Server status refreshes automatically",
            ["Home"] = "Home",
            ["Home.Description"] = "Everything at a glance.",
            ["Servers"] = "Servers",
            ["Servers.Description"] = "Start, stop, and manage your game servers.",
            ["Minecraft"] = "Minecraft",
            ["Minecraft.Description"] = "Vanilla Minecraft server management.",
            ["Palworld"] = "Palworld",
            ["Palworld.Description"] = "Vanilla Palworld server management.",
            ["RemoteAccess"] = "Remote Access",
            ["RemoteAccess.Description"] = "Official Playit access from outside your home.",
            ["Backups"] = "Backups",
            ["Backups.Description"] = "Backup history, schedules, and restore.",
            ["Updates"] = "Updates",
            ["Updates.Description"] = "Installed versions and update status.",
            ["Resources"] = "Resources",
            ["Resources.Description"] = "CPU, memory, and priority profiles.",
            ["Network"] = "Network",
            ["Network.Description"] = "Remote access and how players reach you.",
            ["Files"] = "Files",
            ["Files.Description"] = "Files inside registered server roots.",
            ["Logs"] = "Logs",
            ["Logs.Description"] = "Agent and game server logs.",
            ["Settings"] = "Settings",
            ["Settings.Description"] = "Application, startup, language, and theme.",
            ["About"] = "About",
            ["About.Description"] = "Version, diagnostics, and release information.",
            // Build 6 shell and page strings.
            ["Shell.CollapseSidebar"] = "Collapse sidebar",
            ["Shell.ExpandSidebar"] = "Expand sidebar",
            ["Shell.Refresh"] = "Refresh",
            ["Status.Running"] = "Running",
            ["Status.Stopped"] = "Stopped",
            ["Status.Starting"] = "Starting",
            ["Status.Stopping"] = "Stopping",
            ["Status.Online"] = "Online",
            ["Status.Offline"] = "Offline",
            ["Status.NeedsAttention"] = "Needs attention",
            ["Status.Checking"] = "Checking…",
            ["Status.Unavailable"] = "Unavailable",
            ["Home.AllGood"] = "Everything looks good",
            ["Home.NeedsAttention"] = "Something needs your attention",
            ["Home.Connecting"] = "Connecting to the local service…",
            ["Home.Unreachable"] = "1Salem can't reach its background service",
            ["Home.BackupOverdue"] = "Your backups are out of date",
            ["RemoteAccess.Reachable"] = "Reachable from the internet",
            ["RemoteAccess.Unreachable"] = "Not reachable from the internet",
            ["RemoteAccess.NotSetUp"] = "Local network only",
            ["Home.Servers"] = "Servers",
            ["Home.RemoteAccess"] = "Remote access",
            ["Home.Backups"] = "Backups",
            ["Metric.Players"] = "Players",
            ["Metric.Uptime"] = "Uptime",
            ["Metric.Memory"] = "Memory",
            ["Metric.Cpu"] = "CPU",
            ["Action.Start"] = "Start",
            ["Action.Stop"] = "Stop",
            ["Action.Restart"] = "Restart",
            ["Action.Open"] = "Open",
            ["Action.Manage"] = "Manage",
            ["Action.Retry"] = "Retry",
            ["Action.ViewDetails"] = "View details",
            ["Action.CreateBackup"] = "Create Backup",
            ["Advanced.Title"] = "Advanced details",
            ["Empty.NoServers"] = "No servers yet",
            ["Empty.NoServersMessage"] = "Add a Minecraft or Palworld server to get started.",
            ["Empty.AddServer"] = "Add Server",
            ["Error.ServiceUnavailable"] = "1Salem can't reach its background service.",
            ["Error.ServiceHint"] = "Your servers keep running. 1Salem just can't show or control them right now.",
            ["Error.StatusUnavailable"] = "Server status is temporarily unavailable.",
            ["Error.Retry"] = "Try Again",
            ["Backup.None"] = "No backups yet",
            ["Backup.Today"] = "Backed up today",
            ["Backup.DaysAgo"] = "Last backup {0} days ago",
            ["Backup.Unknown"] = "Backup status unknown",
            ["Backups.AcrossServers"] = "Across {0} servers",
            ["Home.Detail.Running"] = "{0} of {1} running",
            ["Home.Detail.NoneRunning"] = "{0} configured, none running",
            ["Home.Detail.Players"] = "{0} of {1} running, {2} players online",
            ["Home.Detail.PlayersUnknown"] = "{0} of {1} running, player count unavailable",
            ["Home.Stale"] = "Showing the last known state from {0}.",
            ["Network.PublicAddress"] = "Public address",
            ["Network.LocalPort"] = "Local port {0}",
            ["Action.Copy"] = "Copy",
            ["Action.MoreActions"] = "More actions",
            ["Settings.Version"] = "Version",
            ["Settings.Category.General"] = "General",
            ["Settings.Category.Appearance"] = "Appearance",
            ["Settings.Category.Backups"] = "Backups",
            ["Settings.Category.Network"] = "Network",
            ["Settings.Category.Updates"] = "Updates",
            ["Settings.Category.Advanced"] = "Advanced",
            ["Settings.Category.About"] = "About",
            ["Settings.NextStage"] = "This section is part of the next stage of the interface update.",
            ["ServerTab.Overview"] = "Overview",
            ["ServerTab.Console"] = "Console",
            ["ServerTab.Backups"] = "Backups",
            ["ServerTab.Content"] = "Content",
            ["ServerTab.Settings"] = "Settings",
            ["ServerDetail.AtAGlance"] = "At a glance",
            ["ServerDetail.WhoIsOnline"] = "Who's online",
            ["ServerDetail.NobodyOnline"] = "Nobody is online right now.",
            ["ServerDetail.PlayersUnknown"] = "This server isn't reporting who is online.",
            ["ServerDetail.PlayerListUnavailable"] = "Player names aren't available for this server.",
            ["ServerDetail.Operator"] = "Operator",
            ["Metric.Version"] = "Version",
            ["Action.Back"] = "Back to servers",
            ["Action.CopyAddress"] = "Copy Address",
            ["Action.OpenFolder"] = "Open Folder",
            ["Action.OpenLocation"] = "Open Location",
            ["Action.Diagnostics"] = "Diagnostics",
            ["Action.ForceStop"] = "Force Stop",
            ["Action.Export"] = "Export",
            ["Action.Restore"] = "Restore",
            ["Action.Verify"] = "Verify",
            ["Action.Save"] = "Save",
            ["Action.Done"] = "Done",
            ["Action.CheckUpdates"] = "Check for Updates",
            ["Action.CopyDiagnostics"] = "Copy Diagnostics",
            ["Action.Configure"] = "Configure…",
            ["Action.ResourceGovernor"] = "Resource Governor…",
            ["ServerSettings.Files"] = "Server files",
            ["ServerSettings.LegacyIntro"] = "These controls are unchanged while this part of the interface is rebuilt.",
            ["Confirm.ForceStop"] = "Force stop can lose unsaved world data. Stop the server anyway?",
            ["Confirm.Restore"] = "Restoring replaces the current world with this backup. Continue?",
            ["Confirm.Command"] = "Send the command '{0}'? It can disconnect players or stop the server.",
            ["Console.Connected"] = "Connected",
            ["Console.Disconnected"] = "Not connected",
            ["Console.Send"] = "Send",
            ["Console.Follow"] = "Follow output",
            ["Console.ClearDisplay"] = "Clear",
            ["Console.ClearDisplayHint"] = "Clears what is shown here. Server logs are not deleted.",
            ["Console.CommandLabel"] = "Command to send to the server",
            ["Console.OutputLabel"] = "Server output",
            ["Backups.History"] = "Backup history",
            ["Backups.Tools"] = "Save tools and restore points",
            ["Backups.ByServer"] = "Protection by server",
            ["Backups.Recent"] = "All backups",
            ["Backups.VerifyNewest"] = "Verify newest backup",
            ["Backups.AllProtected"] = "All {0} servers have a recent backup.",
            ["Backups.NeedAttention"] = "{0} of {1} servers need a backup. {2} are up to date.",
            ["BackupHealth.Healthy"] = "Backups are healthy",
            ["BackupHealth.DueSoon"] = "A backup is due soon",
            ["BackupHealth.Overdue"] = "Backups are overdue",
            ["BackupHealth.Failed"] = "A backup failed",
            ["BackupHealth.Unknown"] = "Backup state unknown",
            ["Action.Delete"] = "Delete",
            ["Confirm.RestoreServer"] = "Restoring replaces the current world on '{0}' with this backup. Continue?",
            ["Confirm.DeleteBackup"] = "Permanently delete the backup '{1}' for '{0}'? This cannot be undone.",
            ["Network.Destination"] = "Goes to",
            ["Network.Provider"] = "Provided by",
            ["Network.ProviderPlayit"] = "Playit",
            ["Network.ProviderNone"] = "Not set up",
            ["Network.LocalNetwork"] = "On your own network",
            ["Network.ReachableDetail"] = "Share the public address below and people can join from anywhere.",
            ["Network.UnreachableDetail"] = "This server is set up for internet play, but nobody can reach it right now.",
            ["Network.LocalOnlyDetail"] = "Only people on your own network can join. No internet address is set up.",
            ["Network.Verified"] = "verified",
            ["Network.Unverified"] = "not verified",
            ["Network.Adapter"] = "Network adapter",
            ["Network.Details"] = "Network Details",
            ["Action.DeleteServer"] = "Delete Server",
            ["Action.Cancel"] = "Cancel",
            ["Confirm.DeleteServerTitle"] = "Delete {0}?",
            ["Confirm.DeleteServerBody"] = "{0} will be removed from 1Salem Server Manager. It will no longer be listed, started, backed up or scheduled here, and its backup history will no longer be shown.\n\nNo files are deleted. The server folder, its worlds and its backup files stay on disk.",
            ["Server.Running"] = "Server is running",
            ["Server.StopBeforeDelete"] = "This server is currently running. Stop it before deleting it.",
            ["Server.DeleteFailed"] = "Delete failed",
            ["Server.Deleted"] = "Server deleted",
            ["Server.DeletedMessage"] = "{0} was removed from 1Salem Server Manager. Its files were not deleted.",
            ["Server.DeleteBusy"] = "The server is busy with another operation. Try again when it finishes.",
            ["Server.DeleteNotFound"] = "This server is no longer registered.",
            ["Server.DeleteError"] = "The background service couldn't delete this server. Details are in the logs.",
            ["Error.NeedsAdministrator"] = "1Salem needs administrator rights to show your servers",
            ["Error.NeedsAdministratorHint"] = "Your servers keep running. Restart 1Salem as administrator to see and control them.",
            ["Error.RestartAsAdministrator"] = "Restart as Administrator",
            ["Shell.NeedsAdministrator"] = "Administrator needed",
            ["Network.SetUpRemoteAccess"] = "Set Up Remote Access",
            ["Network.ManageRemoteAccess"] = "Manage Remote Access",
            ["Network.AddressCopied"] = "Address copied.",
            ["Network.ClipboardBusy"] = "The clipboard is busy. Try again.",
            ["Settings.GeneralDescription"] = "How the app behaves while you use it.",
            ["Settings.StartWithWindows"] = "Start 1Salem when you sign in to Windows",
            ["Settings.StartWithWindowsUnavailable"] = "Only the installed app can start with Windows.",
            ["Settings.StartWithWindowsFailed"] = "Windows didn't accept the startup setting.",
            ["Settings.CloseBehaviour"] = "Closing the window keeps 1Salem in the notification area. Your servers keep running either way; closing the window never stops them.",
            ["Settings.Agent.Version"] = "Service version  {0}",
            ["Settings.Agent.Machine"] = "Computer  {0}",
            ["Settings.Agent.DatabaseReady"] = "Database  ready",
            ["Settings.Agent.DatabaseStarting"] = "Database  starting",
            ["Appearance.NotSaved"] = "Applied now, but it couldn't be saved for next time.",
            ["Settings.BackupsPolicy"] = "Backup schedules and retention belong to each server, so they live with that server. The Backups page shows which servers need attention.",
            ["Settings.BackupsPolicyAction"] = "Go to Backups",
            ["Settings.NetworkPolicy"] = "Remote access is set up on the Network page, which also shows the address to share and whether people can reach you.",
            ["Settings.NetworkPolicyAction"] = "Go to Network",
            ["Settings.VersionValue"] = "Version {0}",
            ["Settings.BuildValue"] = "Build {0}",
            ["Settings.AdvancedIntro"] = "Troubleshooting tools. You don't need any of this for normal use.",
            ["Settings.OpenDataFolder"] = "Open Data Folder",
            ["Settings.OpenLogs"] = "Open Logs",
            ["Settings.CopyServiceInfo"] = "Copy Details",
            ["Settings.ServiceInformation"] = "Background service",
            ["Settings.Copyright"] = "Copyright © 1Salem",
            ["Updates.Details"] = "Update details",
            ["Updates.CurrentVersion"] = "Current version",
            ["Updates.LatestVersion"] = "Latest version",
            ["Updates.Status"] = "Status",
            ["Updates.CheckNow"] = "Check Now",
            ["Updates.Download"] = "Download Update",
            ["Updates.Install"] = "Update Now",
            ["Updates.Channel"] = "Release channel",
            ["Updates.Channel.Stable"] = "Stable",
            ["Updates.Channel.Preview"] = "Preview",
            ["Updates.Channel.Development"] = "Development",
            ["Updates.AutomaticChecks"] = "Check for updates automatically",
            ["Updates.SavePreferences"] = "Save",
            ["Updates.Components"] = "Installed components",
            ["Updates.Component.Client"] = "App",
            ["Updates.Component.Agent"] = "Background service",
            ["Updates.Component.Updater"] = "Updater",
            ["Updates.Component.Channel"] = "Channel",
            ["Updates.ReleaseNotes"] = "Release notes",
            ["Updates.History"] = "Update history",
            ["Updates.NotChecked"] = "Not checked",
            ["Updates.Loading"] = "Getting update status…",
            ["Updates.Unavailable"] = "Update status is unavailable right now.",
            ["Updates.NotCheckedYet"] = "Update status not checked yet.",
            ["Updates.UpToDate"] = "1Salem is up to date. Last checked {0}.",
            ["Updates.Available"] = "An update is available. Open Update details to download and install it.",
            ["Updates.ReadyToInstall"] = "An update is downloaded and verified, ready to install.",
            ["Updates.LastStepFailed"] = "The last update step didn't work. Try checking again.",
            ["Updates.GameServerBusy"] = "A game server is running. The app can update now; the background service updates at its next safe restart.",
            ["Updates.LastChecked"] = "Last checked: {0}",
            ["Updates.Never"] = "never",
            ["Updates.InstalledHistory"] = "Last update: {0} · Previous: {1} · Rollback: {2}",
            ["Updates.NotRecorded"] = "not recorded",
            ["Updates.None"] = "none",
            ["Updates.Signed"] = "This build is digitally signed.",
            ["Updates.Unsigned"] = "This build is not digitally signed. Update packages are still checked for exact size and SHA-256 before installing.",
            ["Updates.NoRollback"] = "No rollback has been needed.",
            ["Updates.DownloadHint"] = "Download and verify the available update.",
            ["Updates.DownloadDisabledHint"] = "Check for an update first.",
            ["Updates.InstallHint"] = "Install the verified update. The current version is kept so it can roll back.",
            ["Updates.InstallDisabledHint"] = "Download and verify an update before installing.",
            ["Updates.PreferencesSaved"] = "Update preferences saved.",
            ["Updates.PreferencesFailed"] = "Update preferences could not be saved.",
            ["Updates.PrepareFailed"] = "The update could not be prepared for installing.",
            ["Updates.LaunchFailed"] = "The updater could not be started.",
            ["Updates.Working"] = "Working…",
            ["Updates.ActionFailed"] = "That update step didn't work. Try again.",
            ["Updates.Stage.Idle"] = "Idle",
            ["Updates.Stage.Checking"] = "Checking for updates…",
            ["Updates.Stage.Available"] = "Update available",
            ["Updates.Stage.Downloading"] = "Downloading the update…",
            ["Updates.Stage.Verified"] = "Downloaded and verified",
            ["Updates.Stage.ReadyToInstall"] = "Ready to install",
            ["Updates.Stage.Installing"] = "Installing the update…",
            ["Updates.Stage.Succeeded"] = "Updated",
            ["Updates.Stage.Failed"] = "Failed",
            ["Updates.Stage.RolledBack"] = "Rolled back",
            ["Updates.Stage.FullSetupRequired"] = "Needs the full installer",
            ["Updates.Stage.UpdatePendingRestart"] = "Finishes after a restart",
            ["Updates.Stage.InstalledVersionNewer"] = "Installed version is newer",
            ["Updates.Stage.IncompleteComponentUpdate"] = "Update incomplete",
            ["Backups.None"] = "No backups have been taken for this server yet.",
            ["Backups.NoneAnywhere"] = "No backups have been taken yet.",
            ["Backups.ListUnavailable"] = "Some backups couldn't be listed right now. Try again in a moment.",
            ["Backups.OpenServerName"] = "Open {0} backups",
            ["Backups.RestoreName"] = "Restore {0} ({1})",
            ["Backups.VerifyName"] = "Verify {0} ({1})",
            ["Backups.DeleteName"] = "Delete {0} ({1})",
            ["Backups.Error.Busy"] = "The server is busy with another operation. Try again when it finishes.",
            ["Backups.Error.NotFound"] = "That backup no longer exists.",
            ["Backups.Error.Failed"] = "The background service couldn't complete this. Details are in the logs.",
            ["Confirm.RestoreBackup"] = "Restoring replaces the current world on '{0}' with the backup '{1}'. Continue?",
            ["Backups.Files"] = "{0} files",
            ["Backups.Protected"] = "Protected",
            ["Backups.Status.Completed"] = "Complete",
            ["Backups.Status.Failed"] = "Failed",
            ["Backups.Status.Corrupt"] = "Damaged",
            ["Backups.Status.Pending"] = "Pending",
            ["Content.Subtitle"] = "Add-ons for this server.",
            ["Content.MinecraftSubtitle"] = "Plugins for this Minecraft server, from Hangar and Modrinth.",
            ["Content.PalworldSubtitle"] = "Add-ons for this Palworld server.",
            ["Content.ComingTitle"] = "Nothing to install yet",
            ["Content.ComingMessage"] = "Browsing and installing add-ons arrives in a later update. This server keeps running exactly as it is.",
            ["Action.Close"] = "Close",
            ["Content.Discover"] = "Discover",
            ["Content.Installed"] = "Installed",
            ["Content.Updates"] = "Updates",
            ["Content.Details"] = "Details",
            ["Content.CompatibleOnly"] = "Works with this server",
            ["Content.SearchLabel"] = "Search plugins",
            ["Content.SortLabel"] = "Sort",
            ["Content.ProviderLabel"] = "Source",
            ["Content.ResultsList"] = "Plugin results",
            ["Content.Sort.Relevance"] = "Best match",
            ["Content.Sort.Downloads"] = "Most downloaded",
            ["Content.Sort.Updated"] = "Recently updated",
            ["Content.Sort.Newest"] = "Newest",
            ["Content.Provider.All"] = "All sources",
            ["Content.Install"] = "Install",
            ["Content.AlreadyInstalled"] = "Installed",
            ["Content.Update"] = "Update",
            ["Content.Rollback"] = "Go back",
            ["Content.Uninstall"] = "Remove",
            ["Content.ViewProject"] = "View project",
            ["Content.ViewOn"] = "View on {0}",
            ["Content.ByAuthor"] = "by {0}",
            ["Content.Source"] = "Source: {0}",
            ["Content.SourceUnknown"] = "Source: unknown",
            ["Content.Downloads"] = "{0} downloads",
            ["Content.MinecraftVersion"] = "Minecraft {0}",
            ["Content.Unknown"] = "Unknown",
            ["Content.VersionUnknown"] = "Version unknown",
            ["Content.VersionNamed"] = "Version {0}",
            ["Content.UpdateFromTo"] = "{0} to {1}",
            ["Content.InstallNamed"] = "Install {0}",
            ["Content.UpdateNamed"] = "Update {0}",
            ["Content.UninstallNamed"] = "Remove {0}",
            ["Content.RestartRequired"] = "Restart the server to load it.",
            ["Content.Done"] = "Done.",
            ["Content.State.UpToDate"] = "Up to date",
            ["Content.State.UpdateAvailable"] = "Update available",
            ["Content.State.RestartRequired"] = "Restart required",
            ["Content.State.InstalledManually"] = "Added by you",
            ["Content.State.MissingFile"] = "File missing",
            ["Content.State.ModifiedLocally"] = "Changed on disk",
            ["Content.State.UnknownVersion"] = "Version unknown",
            ["Content.Channel.Release"] = "Release",
            ["Content.Channel.Beta"] = "Beta",
            ["Content.Channel.Alpha"] = "Alpha",
            ["Content.Details.Facts"] = "Details",
            ["Content.Details.About"] = "About this plugin",
            ["Content.Details.LatestCompatible"] = "Newest that fits",
            ["Content.Details.Platforms"] = "Server software",
            ["Content.Details.GameVersions"] = "Minecraft versions",
            ["Content.Details.License"] = "Licence",
            ["Content.Details.Dependencies"] = "Also needs",
            ["Content.Details.NoCompatible"] = "Nothing that fits this server",
            ["Content.Details.NoDependencies"] = "Nothing else",
            ["Content.Loading"] = "Loading",
            ["Content.LoadingMessage"] = "Asking the plugin sites.",
            ["Content.Empty.Title"] = "No plugins found",
            ["Content.Empty.Message"] = "Try different words, or turn off \"Works with this server\" to see more.",
            ["Content.NoInstalled.Title"] = "No plugins yet",
            ["Content.NoInstalled.Message"] = "Anything you install appears here, along with plugins you added yourself.",
            ["Content.NoUpdates.Title"] = "Everything is up to date",
            ["Content.NoUpdates.Message"] = "No updates that fit this server are waiting.",
            ["Content.Unsupported.Title"] = "Plugins are not available here",
            ["Content.Unsupported.Vanilla"] = "This server does not support plugins. Vanilla Minecraft has no plugin system, while Paper, Purpur, Spigot and Bukkit servers do.",
            ["Content.Unsupported.UnknownPlatform"] = "The server software could not be identified, so no plugins are offered.",
            ["Content.Unsupported.UnknownVersion"] = "The Minecraft version could not be read, so nothing can be checked for compatibility.",
            ["Content.Unsupported.MissingRoot"] = "The server folder could not be found.",
            ["Content.Unsupported.NotMinecraft"] = "Plugins are a Minecraft feature.",
            ["Content.Stage.Downloading"] = "Downloading and checking.",
            ["Content.Stage.Removing"] = "Removing.",
            ["Content.Installed.Title"] = "Plugin installed",
            ["Content.Installed.Message"] = "Ready to use.",
            ["Content.Install.FailedTitle"] = "Could not install",
            ["Content.Install.BlockedTitle"] = "Nothing was installed",
            ["Content.Updated.Title"] = "Plugin updated",
            ["Content.Update.FailedTitle"] = "Could not update",
            ["Content.RolledBack.Title"] = "Earlier version restored",
            ["Content.Rollback.FailedTitle"] = "Could not go back",
            ["Content.Uninstalled.Title"] = "Plugin removed",
            ["Content.Uninstall.FailedTitle"] = "Could not remove",
            ["Content.Dependencies.Title"] = "Install plugin",
            ["Content.Dependencies.Heading"] = "{0} needs other plugins",
            ["Content.Dependencies.Body"] = "These are installed as well, because the plugin will not run without them.",
            ["Content.Dependencies.Confirm"] = "Install all",
            ["Content.Uninstall.Title"] = "Remove plugin",
            ["Content.Uninstall.Heading"] = "Remove {0}?",
            ["Content.Uninstall.Body"] = "The plugin file is removed from this server. Its settings folder is kept, so installing it again restores your configuration.",
            ["Content.Uninstall.Confirm"] = "Remove plugin",
            ["Content.Error.AgentTitle"] = "Cannot reach the background service",
            ["Content.Error.AgentMessage"] = "1Salem Server Manager could not reach its background service.",
            ["Content.Error.ProvidersTitle"] = "Plugin sites unavailable",
            ["Content.Error.ProvidersMessage"] = "Hangar and Modrinth could not be reached just now. Try again in a moment.",
            ["Content.Error.Offline"] = "There is no internet connection.",
            ["Content.Error.RateLimited"] = "The plugin site asked us to slow down. Try again shortly.",
            ["Content.Error.ApiRetired"] = "The plugin site changed how it works. Update 1Salem Server Manager.",
            ["Content.Error.HashMismatch"] = "The download did not match the site's own checksum, so it was thrown away.",
            ["Content.Error.InvalidJar"] = "The download was not a valid plugin file.",
            ["Content.Error.ServerBusy"] = "The server is busy with another job. Try again when it finishes.",
            ["Content.Error.FileInUse"] = "The server is using that file. Stop the server and try again.",
            ["Content.Error.AccessDenied"] = "Windows refused access to the plugins folder.",
            ["Content.Error.NoCompatibleVersion"] = "No release fits this server's Minecraft version.",
            ["Content.Error.NoRollback"] = "There is no earlier version stored to go back to.",
            ["Content.Error.AlreadyCurrent"] = "That plugin is already up to date.",
            ["Content.Error.DependencyIncompatible"] = "A plugin it needs has no version for this server, so nothing was installed.",
            ["Content.Error.DependencyUnresolvable"] = "A plugin it needs could not be found automatically, so nothing was installed.",
            ["Content.Error.Generic"] = "That did not work. Nothing was changed.",
            ["Content.Error.LinkTitle"] = "Could not open the link",
            ["Content.Error.LinkMessage"] = "The browser could not be opened.",
            ["Content.KindLabel"] = "Type",
            ["Content.Kind.Plugin"] = "Plugin",
            ["Content.Kind.Modpack"] = "Modpack",
            ["Content.Kind.DataPack"] = "Data Pack",
            ["Content.Kind.ResourcePack"] = "Resource Pack",
            ["Content.CreateServer"] = "Create server",
            ["Content.CreateServerNamed"] = "Create a server from {0}",
            ["Content.Distribute"] = "Use on this server",
            ["Content.DistributeNamed"] = "Send {0} to players joining this server",
            ["Content.Withdraw"] = "Stop sending",
            ["Content.State.ReloadRequired"] = "Reload required",
            ["Content.State.Incompatible"] = "Made for another version",
            ["Content.State.NotDistributed"] = "Downloaded",
            ["Content.State.Distributed"] = "Sent to players",
            ["Content.State.RequiresMigration"] = "Requires server migration",
            ["Content.MigrationNeeded"] = "Version {0} needs a different Minecraft version or loader, so it cannot be applied as an update.",
            ["Content.Distributed.Title"] = "Players will be offered this pack",
            ["Content.Distributed.Message"] = "They get it when they next connect.",
            ["Content.Distribute.FailedTitle"] = "Could not change the resource pack",
            ["Content.Withdrawn.Title"] = "Players will no longer be offered a pack",
            ["Content.Stage.ResolvingPack"] = "Reading the pack.",
            ["Content.Stage.BuildingServer"] = "Building the new server.",
            ["Content.Modpack.Title"] = "Create a server from a modpack",
            ["Content.Modpack.Subtitle"] = "A modpack decides the Minecraft version, the loader and every mod, so it always builds a new server. Nothing on your existing servers changes.",
            ["Content.Modpack.Loader"] = "Mod loader",
            ["Content.Modpack.PackVersion"] = "Pack version",
            ["Content.Modpack.Size"] = "Download",
            ["Content.Modpack.SizeValue"] = "{0} files, about {1}",
            ["Content.Modpack.ServerName"] = "Server name",
            ["Content.Modpack.Location"] = "Where to put it",
            ["Content.Modpack.Port"] = "Port",
            ["Content.Modpack.Browse"] = "Browse",
            ["Content.Modpack.Eula"] = "I accept the Minecraft End User Licence Agreement",
            ["Content.Modpack.Create"] = "Create server",
            ["Content.Modpack.NeedName"] = "Give the server a name.",
            ["Content.Modpack.NeedLocation"] = "Choose a folder for the server.",
            ["Content.Modpack.NeedPort"] = "Enter a port between 1 and 65535.",
            ["Content.Modpack.NeedEula"] = "Minecraft's licence has to be accepted before a server can run.",
            ["Content.Modpack.FolderNotEmpty"] = "That folder already has files in it. Choose an empty or new folder.",
            ["Content.Modpack.LoaderUnsupported"] = "This pack needs the {0} loader, which comes with its own installer program. 1Salem Server Manager does not run other installers, so this pack cannot be set up here yet. Fabric packs work.",
            ["Content.Modpack.UnsafePack"] = "This pack asks to write files outside the server folder, or from a site the provider does not allow. Nothing was downloaded.",
            ["Content.Modpack.UnreadablePack"] = "This pack's index could not be read, so nothing was downloaded.",
            ["Content.Modpack.TooLarge"] = "This pack is larger than this app will download in one go.",
            ["Content.Modpack.CreatedTitle"] = "Server created",
            ["Content.Modpack.CreatedMessage"] = "{0} is ready on Minecraft {1}. Start it from the Servers page.",
            ["Content.Modpack.FailedTitle"] = "Could not create the server",
            ["Content.Error.NeedsReachableUrl"] = "Players need a web address for the pack, and this one has none. This app does not host files or open ports.",
            ["Content.Error.NoSha1"] = "The provider did not publish the checksum Minecraft needs for this.",
            ["Content.Error.PackTooLarge"] = "Minecraft refuses server resource packs larger than 250 MiB.",
            ["Content.Error.NoWorld"] = "The server's world could not be identified from its settings, so there is nowhere safe to put this.",
            ["Content.Error.InvalidArchive"] = "The download was not a valid pack.",
            ["Content.Error.DestinationNotEmpty"] = "That folder already has files in it.",
            ["Content.Error.EulaRequired"] = "Minecraft's licence has to be accepted first.",
            ["Content.Error.JavaMissing"] = "No suitable Java runtime was found for this pack.",
            ["Content.Error.FileUnavailable"] = "A file the pack needs could not be downloaded or did not match its checksum. Nothing was kept.",
            ["Content.Error.UnsupportedServer"] = "This server cannot take that kind of content.",
            ["Content.Error.PortInUse"] = "Another server on this computer is already set up for that port. Choose a different one.",
            ["Content.Error.RegistrationFailed"] = "The new server could not be registered, so nothing was kept.",
            ["ServerSettings.General"] = "General",
            ["ServerSettings.Game"] = "Game",
            ["ServerSettings.Network"] = "Network",
            ["ServerSettings.Resources"] = "Resources",
            ["ServerSettings.Advanced"] = "Advanced",
            ["ServerSettings.AutoStart"] = "Start this server when the computer starts",
            ["ServerSettings.AutoRestart"] = "Restart automatically if it stops unexpectedly",
            ["ServerSettings.Updates"] = "Server updates",
            ["ServerSettings.UpdatesUnknown"] = "Update status not checked yet.",
            ["ServerSettings.UpToDate"] = "This server is up to date.",
            ["ServerSettings.UpdateAvailable"] = "Version {0} is available.",
            ["ServerSettings.GameBody"] = "World and gameplay options for this server.",
            ["ServerSettings.NetworkBody"] = "How players reach this server, and the address to share with them.",
            ["ServerSettings.ResourcesBody"] = "Memory and processor limits. These settings apply to every server on this PC, not only this one.",
            ["ServerSettings.AdvancedIntro"] = "Technical information for troubleshooting. You don't need any of this for normal use.",
            ["Advanced.Threads"] = "Threads",
            ["Advanced.Management"] = "Local management",
            ["Advanced.RestPort"] = "Management port",
            ["Advanced.Connected"] = "connected",
            ["Advanced.Disconnected"] = "not connected",
            ["Advanced.PortOpen"] = "open",
            ["Advanced.PortClosed"] = "closed",
            ["Error.ActionFailed"] = "That didn't work",
            ["Error.FolderUnavailable"] = "This server's folder could not be found.",
            ["Advanced.RootProcess"] = "Root process",
            ["Advanced.GameProcess"] = "Game process",
            ["Advanced.ChildProcesses"] = "Child processes",
            ["Advanced.Port"] = "Port",
            ["Appearance.Title"] = "Language and Theme",
            ["Appearance.Description"] = "Changes apply immediately and are saved for the next launch.",
            ["Appearance.Language"] = "Language",
            ["Appearance.Theme"] = "Theme",
            ["Appearance.English"] = "English",
            ["Appearance.Arabic"] = "العربية",
            ["Appearance.Dark"] = "Dark",
            ["Appearance.Light"] = "Light",
            ["Appearance.FollowWindows"] = "Follow Windows",
            ["Appearance.Apply"] = "Apply",
            ["Appearance.Applied"] = "Language and theme applied.",
            ["Appearance.ScopeDescription"] = "Dashboard appearance is separate from each server's Auto Start and Auto Restart settings.",
            ["Shell.Navigation"] = "☰ Navigation",
            ["Shell.ShowNavigation"] = "☰ Show Navigation",
            ["Shell.HideNavigation"] = "☰ Hide Navigation",
            ["Shell.AdministratorTools"] = "Administrator Tools",
            ["Shell.AdministratorMode"] = "Administrator mode",
            ["Shell.NormalMode"] = "Normal mode",
            ["Shell.Connected"] = "Connected",
            ["Shell.AgentUnavailable"] = "Not connected",
            ["Shell.Connecting"] = "Connecting…",
            ["Shell.Footer"] = "Server status refreshes automatically",
            ["Shell.Dismiss"] = "Dismiss",
            ["Palworld.Overview.Title"] = "Live server overview",
            ["Palworld.Overview.Loading"] = "Loading…",
            ["Palworld.Overview.LoadingLiveData"] = "Loading live server data",
            ["Palworld.Overview.Unavailable"] = "Unavailable",
            ["Palworld.Overview.Stale"] = "Stale",
            ["Palworld.Overview.ServerStopped"] = "Server stopped",
            ["Palworld.Overview.RuntimeUnavailable"] = "Runtime unavailable",
            ["Palworld.Overview.LivePlayers"] = "Live player count",
            ["Palworld.Overview.LiveRestMetric"] = "Live REST metric",
            ["Palworld.Overview.ProcessUptime"] = "Process uptime",
            ["Palworld.Overview.LogicalProcessors"] = "{0} logical processors",
            ["Palworld.Overview.WarningAt"] = "Warning at {0}",
            ["Palworld.Overview.WorkingSet"] = "Process working set",
            ["Palworld.Overview.NoBackup"] = "No backup recorded",
            ["Palworld.Overview.PercentOfWarning"] = "{0:0}% of {1} warning threshold",
            ["Palworld.Overview.WarningUnavailable"] = "Warning threshold unavailable",
            ["Palworld.Overview.DiskFree"] = "{0} free",
            ["Palworld.Overview.DaysAgo"] = "{0}d ago",
            ["Palworld.Overview.HoursAgo"] = "{0}h ago",
            ["Palworld.Overview.MinutesAgo"] = "{0}m ago",
            ["Palworld.Overview.Status"] = "Status",
            ["Palworld.Overview.QuickActions"] = "Quick Actions",
            ["Palworld.Overview.ServerActivity"] = "Server Activity",
            ["Palworld.Overview.RecentActivity"] = "Recent Activity",
            ["Palworld.Overview.ResourceSummary"] = "Resource Summary",
            ["Palworld.Overview.Connections"] = "Connections",
            ["Palworld.Overview.LocalNetwork"] = "Local Network",
            ["Palworld.Overview.InternetPlayit"] = "Internet / Playit",
            ["Palworld.Overview.NoHistory"] = "History will appear as live samples arrive.",
            ["Palworld.Overview.NoActivity"] = "No recent server activity.",
            ["Palworld.Overview.TimeRange"] = "Time range",
            ["Palworld.Overview.Badge.ProcessRunning"] = "Process Running",
            ["Palworld.Overview.Badge.PortOpen"] = "Port Open",
            ["Palworld.Overview.Badge.GameReady"] = "Game Ready",
            ["Palworld.Overview.Badge.RestConnected"] = "REST Connected",
            ["Palworld.Overview.Badge.PlayitOnline"] = "Playit Online",
            ["Palworld.Overview.Badge.PublicMappingValid"] = "Public Mapping Valid",
            ["Palworld.Overview.Metric.Players"] = "Players",
            ["Palworld.Overview.Metric.Fps"] = "Server FPS",
            ["Palworld.Overview.Metric.Uptime"] = "Uptime",
            ["Palworld.Overview.Metric.Cpu"] = "CPU",
            ["Palworld.Overview.Metric.Ram"] = "RAM",
            ["Palworld.Overview.Metric.LastBackup"] = "Last Backup",
            ["Palworld.Overview.Action.Start"] = "Start Server",
            ["Palworld.Overview.Action.Refresh"] = "Refresh",
            ["Palworld.Overview.Action.SaveWorld"] = "Save World",
            ["Palworld.Overview.Action.Announcement"] = "Announcement",
            ["Palworld.Overview.Action.GracefulStop"] = "Graceful Stop",
            ["Palworld.Overview.Action.Restart"] = "Restart",
            ["Palworld.Overview.Action.BackupNow"] = "Backup Now",
            ["Palworld.Overview.Action.CopyInternet"] = "Copy Internet Address",
            ["Palworld.Overview.Action.Copy"] = "Copy",
            ["Palworld.Overview.Action.Send"] = "Send",
            ["Palworld.Overview.Action.Cancel"] = "Cancel",
            ["Palworld.Overview.AnnouncementHint"] = "Message to connected players",
            ["Palworld.Overview.Resource.Cpu"] = "CPU usage",
            ["Palworld.Overview.Resource.Ram"] = "RAM usage",
            ["Palworld.Overview.Resource.Disk"] = "Disk usage",
            ["Palworld.Overview.Activity.Source"] = "Source: {0}",
            ["Palworld.Overview.Activity.Succeeded"] = "Completed",
            ["Palworld.Overview.Activity.Failed"] = "Failed"
        };

    private static readonly IReadOnlyDictionary<string, string> Arabic =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppTitle"] = "مدير خوادم 1Salem",
            ["DashboardSubtitle"] = "لوحة تحكم أصلية للخوادم",
            ["AgentConnection"] = "اتصال الوكيل",
            ["Refresh"] = "تحديث",
            ["AgentPc"] = "جهاز الوكيل",
            ["AgentVersion"] = "إصدار الوكيل",
            ["Database"] = "قاعدة البيانات",
            ["FoundationTitle"] = "أساس إدارة الخوادم",
            ["FoundationDescription"] = "تتوفر إدارة العمليات والنسخ الاحتياطية الموثقة وتثبيت الألعاب وحماية الموارد من أقسامها.",
            ["Footer"] = "اتصال محلي آمن | واجهة محلية | عمليات تحافظ على البيانات",
            ["Home"] = "الرئيسية",
            ["Home.Description"] = "كل شيء في لمحة.",
            ["Servers"] = "الخوادم",
            ["Servers.Description"] = "تشغيل وإيقاف وإدارة خوادم الألعاب.",
            ["Minecraft"] = "ماينكرافت",
            ["Minecraft.Description"] = "إدارة خادم ماينكرافت الأصلي.",
            ["Palworld"] = "بال وورلد",
            ["Palworld.Description"] = "إدارة خادم بال وورلد الأصلي.",
            ["RemoteAccess"] = "الوصول من خارج المنزل",
            ["RemoteAccess.Description"] = "إدارة الوصول الخارجي عبر وكيل Playit الرسمي.",
            ["Backups"] = "النسخ الاحتياطية",
            ["Backups.Description"] = "السجل والجدولة والاستعادة.",
            ["Updates"] = "التحديثات",
            ["Updates.Description"] = "الإصدارات المثبتة وحالة التحديث.",
            ["Resources"] = "الموارد",
            ["Resources.Description"] = "ملفات تعريف المعالج والذاكرة والأولوية.",
            ["Network"] = "الشبكة",
            ["Network.Description"] = "الوصول عن بُعد وكيفية اتصال اللاعبين بك.",
            ["Files"] = "الملفات",
            ["Files.Description"] = "الملفات داخل مجلدات الخوادم المسجلة.",
            ["Logs"] = "السجلات",
            ["Logs.Description"] = "سجلات الوكيل وخوادم الألعاب.",
            ["Settings"] = "الإعدادات",
            ["Settings.Description"] = "التطبيق وبدء التشغيل واللغة والمظهر.",
            ["About"] = "حول",
            ["About.Description"] = "الإصدار والتشخيصات ومعلومات الإصدار.",
            ["Shell.CollapseSidebar"] = "طي الشريط الجانبي",
            ["Shell.ExpandSidebar"] = "توسيع الشريط الجانبي",
            ["Shell.Refresh"] = "تحديث",
            ["Status.Running"] = "قيد التشغيل",
            ["Status.Stopped"] = "متوقف",
            ["Status.Starting"] = "جارٍ التشغيل",
            ["Status.Stopping"] = "جارٍ الإيقاف",
            ["Status.Online"] = "متصل",
            ["Status.Offline"] = "غير متصل",
            ["Status.NeedsAttention"] = "يحتاج إلى انتباه",
            ["Status.Checking"] = "جارٍ الفحص…",
            ["Status.Unavailable"] = "غير متاح",
            ["Home.AllGood"] = "كل شيء يبدو على ما يرام",
            ["Home.NeedsAttention"] = "هناك ما يحتاج إلى انتباهك",
            ["Home.Connecting"] = "جارٍ الاتصال بالخدمة المحلية…",
            ["Home.Unreachable"] = "تعذّر على 1Salem الوصول إلى خدمته الخلفية",
            ["Home.BackupOverdue"] = "نسخك الاحتياطية قديمة",
            ["RemoteAccess.Reachable"] = "يمكن الوصول إليه من الإنترنت",
            ["RemoteAccess.Unreachable"] = "لا يمكن الوصول إليه من الإنترنت",
            ["RemoteAccess.NotSetUp"] = "الشبكة المحلية فقط",
            ["Home.Servers"] = "الخوادم",
            ["Home.RemoteAccess"] = "الوصول عن بُعد",
            ["Home.Backups"] = "النسخ الاحتياطية",
            ["Metric.Players"] = "اللاعبون",
            ["Metric.Uptime"] = "مدة التشغيل",
            ["Metric.Memory"] = "الذاكرة",
            ["Metric.Cpu"] = "المعالج",
            ["Action.Start"] = "تشغيل",
            ["Action.Stop"] = "إيقاف",
            ["Action.Restart"] = "إعادة تشغيل",
            ["Action.Open"] = "فتح",
            ["Action.Manage"] = "إدارة",
            ["Action.Retry"] = "إعادة المحاولة",
            ["Action.ViewDetails"] = "عرض التفاصيل",
            ["Action.CreateBackup"] = "إنشاء نسخة احتياطية",
            ["Advanced.Title"] = "تفاصيل متقدمة",
            ["Empty.NoServers"] = "لا توجد خوادم بعد",
            ["Empty.NoServersMessage"] = "أضف خادم ماينكرافت أو بال وورلد للبدء.",
            ["Empty.AddServer"] = "إضافة خادم",
            ["Error.ServiceUnavailable"] = "تعذّر على 1Salem الوصول إلى خدمته الخلفية.",
            ["Error.ServiceHint"] = "خوادمك ما زالت تعمل. لكن لا يستطيع 1Salem عرضها أو التحكم بها الآن.",
            ["Error.StatusUnavailable"] = "حالة الخادم غير متاحة مؤقتًا.",
            ["Error.Retry"] = "إعادة المحاولة",
            ["Backup.None"] = "لا توجد نسخ احتياطية بعد",
            ["Backup.Today"] = "تم النسخ الاحتياطي اليوم",
            ["Backup.DaysAgo"] = "آخر نسخة احتياطية قبل {0} يومًا",
            ["Backup.Unknown"] = "حالة النسخ الاحتياطي غير معروفة",
            ["Backups.AcrossServers"] = "عبر {0} خوادم",
            ["Home.Detail.Running"] = "{0} من {1} قيد التشغيل",
            ["Home.Detail.NoneRunning"] = "{0} مُهيأة، ولا يعمل أي منها",
            ["Home.Detail.Players"] = "{0} من {1} قيد التشغيل، و{2} لاعبًا متصلًا",
            ["Home.Detail.PlayersUnknown"] = "{0} من {1} قيد التشغيل، وعدد اللاعبين غير متاح",
            ["Home.Stale"] = "يتم عرض آخر حالة معروفة منذ {0}.",
            ["Network.PublicAddress"] = "العنوان العام",
            ["Network.LocalPort"] = "المنفذ المحلي {0}",
            ["Action.Copy"] = "نسخ",
            ["Action.MoreActions"] = "إجراءات أخرى",
            ["Settings.Version"] = "الإصدار",
            ["Settings.Category.General"] = "عام",
            ["Settings.Category.Appearance"] = "المظهر",
            ["Settings.Category.Backups"] = "النسخ الاحتياطية",
            ["Settings.Category.Network"] = "الشبكة",
            ["Settings.Category.Updates"] = "التحديثات",
            ["Settings.Category.Advanced"] = "متقدم",
            ["Settings.Category.About"] = "حول",
            ["Settings.NextStage"] = "هذا القسم جزء من المرحلة التالية من تحديث الواجهة.",
            ["ServerTab.Overview"] = "نظرة عامة",
            ["ServerTab.Console"] = "وحدة التحكم",
            ["ServerTab.Backups"] = "النسخ الاحتياطية",
            ["ServerTab.Content"] = "المحتوى",
            ["ServerTab.Settings"] = "الإعدادات",
            ["ServerDetail.AtAGlance"] = "نظرة سريعة",
            ["ServerDetail.WhoIsOnline"] = "من المتصل الآن",
            ["ServerDetail.NobodyOnline"] = "لا يوجد أحد متصل الآن.",
            ["ServerDetail.PlayersUnknown"] = "هذا الخادم لا يُبلغ عن المتصلين.",
            ["ServerDetail.PlayerListUnavailable"] = "أسماء اللاعبين غير متاحة لهذا الخادم.",
            ["ServerDetail.Operator"] = "مشرف",
            ["Metric.Version"] = "الإصدار",
            ["Action.Back"] = "العودة إلى الخوادم",
            ["Action.CopyAddress"] = "نسخ العنوان",
            ["Action.OpenFolder"] = "فتح المجلد",
            ["Action.OpenLocation"] = "فتح الموقع",
            ["Action.Diagnostics"] = "التشخيصات",
            ["Action.ForceStop"] = "إيقاف قسري",
            ["Action.Export"] = "تصدير",
            ["Action.Restore"] = "استعادة",
            ["Action.Verify"] = "تحقق",
            ["Action.Save"] = "حفظ",
            ["Action.Done"] = "تم",
            ["Action.CheckUpdates"] = "التحقق من التحديثات",
            ["Action.CopyDiagnostics"] = "نسخ التشخيصات",
            ["Action.Configure"] = "تهيئة…",
            ["Action.ResourceGovernor"] = "منظّم الموارد…",
            ["ServerSettings.Files"] = "ملفات الخادم",
            ["ServerSettings.LegacyIntro"] = "هذه العناصر لم تتغيّر بينما تُعاد بناء هذا الجزء من الواجهة.",
            ["Confirm.ForceStop"] = "قد يؤدي الإيقاف القسري إلى فقدان بيانات عالم غير محفوظة. هل تريد الإيقاف على أي حال؟",
            ["Confirm.Restore"] = "الاستعادة ستستبدل العالم الحالي بهذه النسخة الاحتياطية. هل تريد المتابعة؟",
            ["Confirm.Command"] = "هل تريد إرسال الأمر '{0}'؟ قد يقطع اتصال اللاعبين أو يوقف الخادم.",
            ["Console.Connected"] = "متصل",
            ["Console.Disconnected"] = "غير متصل",
            ["Console.Send"] = "إرسال",
            ["Console.Follow"] = "متابعة المخرجات",
            ["Console.ClearDisplay"] = "مسح",
            ["Console.ClearDisplayHint"] = "يمسح ما يظهر هنا فقط. لا تُحذف سجلات الخادم.",
            ["Console.CommandLabel"] = "الأمر المراد إرساله إلى الخادم",
            ["Console.OutputLabel"] = "مخرجات الخادم",
            ["Backups.History"] = "سجل النسخ الاحتياطية",
            ["Backups.Tools"] = "أدوات الحفظ ونقاط الاستعادة",
            ["Backups.ByServer"] = "الحماية حسب الخادم",
            ["Backups.Recent"] = "كل النسخ الاحتياطية",
            ["Backups.VerifyNewest"] = "التحقق من أحدث نسخة",
            ["Backups.AllProtected"] = "جميع الخوادم الـ {0} لديها نسخة احتياطية حديثة.",
            ["Backups.NeedAttention"] = "{0} من {1} خوادم تحتاج إلى نسخة احتياطية. {2} محدَّثة.",
            ["BackupHealth.Healthy"] = "النسخ الاحتياطية سليمة",
            ["BackupHealth.DueSoon"] = "حان موعد نسخة احتياطية قريبًا",
            ["BackupHealth.Overdue"] = "النسخ الاحتياطية متأخرة",
            ["BackupHealth.Failed"] = "فشلت نسخة احتياطية",
            ["BackupHealth.Unknown"] = "حالة النسخ الاحتياطي غير معروفة",
            ["Action.Delete"] = "حذف",
            ["Confirm.RestoreServer"] = "الاستعادة ستستبدل العالم الحالي على '{0}' بهذه النسخة الاحتياطية. هل تريد المتابعة؟",
            ["Confirm.DeleteBackup"] = "هل تريد حذف النسخة الاحتياطية '{1}' للخادم '{0}' نهائيًا؟ لا يمكن التراجع عن هذا.",
            ["Network.Destination"] = "يوجّه إلى",
            ["Network.Provider"] = "مُقدَّم بواسطة",
            ["Network.ProviderPlayit"] = "Playit",
            ["Network.ProviderNone"] = "غير مُهيأ",
            ["Network.LocalNetwork"] = "على شبكتك المحلية",
            ["Network.ReachableDetail"] = "شارك العنوان العام أدناه ليتمكن الآخرون من الانضمام من أي مكان.",
            ["Network.UnreachableDetail"] = "هذا الخادم مُهيأ للعب عبر الإنترنت، لكن لا أحد يستطيع الوصول إليه الآن.",
            ["Network.LocalOnlyDetail"] = "يمكن الانضمام فقط لمن هم على شبكتك المحلية. لا يوجد عنوان إنترنت مُهيأ.",
            ["Network.Verified"] = "مُتحقق منه",
            ["Network.Unverified"] = "غير مُتحقق منه",
            ["Network.Adapter"] = "محوّل الشبكة",
            ["Network.Details"] = "تفاصيل الشبكة",
            ["Action.DeleteServer"] = "حذف الخادم",
            ["Action.Cancel"] = "إلغاء",
            ["Confirm.DeleteServerTitle"] = "حذف {0}؟",
            ["Confirm.DeleteServerBody"] = "ستتم إزالة {0} من 1Salem Server Manager. لن يظهر هنا بعد الآن، ولن يُشغَّل أو يُنسخ احتياطيًا أو يُجدوَل من هنا، ولن يُعرض سجل نسخه الاحتياطية.\n\nلن يُحذف أي ملف. يبقى مجلد الخادم وعوالمه وملفات نسخه الاحتياطية على القرص.",
            ["Server.Running"] = "الخادم يعمل",
            ["Server.StopBeforeDelete"] = "هذا الخادم يعمل حاليًا. أوقفه قبل حذفه.",
            ["Server.DeleteFailed"] = "فشل الحذف",
            ["Server.Deleted"] = "تم حذف الخادم",
            ["Server.DeletedMessage"] = "تمت إزالة {0} من 1Salem Server Manager. لم تُحذف ملفاته.",
            ["Server.DeleteBusy"] = "الخادم مشغول بعملية أخرى. حاول مرة أخرى عند انتهائها.",
            ["Server.DeleteNotFound"] = "هذا الخادم لم يعد مسجّلًا.",
            ["Server.DeleteError"] = "تعذّر على الخدمة الخلفية حذف هذا الخادم. التفاصيل في السجلات.",
            ["Error.NeedsAdministrator"] = "يحتاج 1Salem إلى صلاحيات المسؤول لعرض خوادمك",
            ["Error.NeedsAdministratorHint"] = "خوادمك تستمر في العمل. أعد تشغيل 1Salem كمسؤول لعرضها والتحكم بها.",
            ["Error.RestartAsAdministrator"] = "إعادة التشغيل كمسؤول",
            ["Shell.NeedsAdministrator"] = "يلزم المسؤول",
            ["Network.SetUpRemoteAccess"] = "إعداد الوصول من خارج المنزل",
            ["Network.ManageRemoteAccess"] = "إدارة الوصول من خارج المنزل",
            ["Network.AddressCopied"] = "تم نسخ العنوان.",
            ["Network.ClipboardBusy"] = "الحافظة مشغولة. حاول مرة أخرى.",
            ["Settings.GeneralDescription"] = "كيفية تصرّف التطبيق أثناء استخدامك له.",
            ["Settings.StartWithWindows"] = "تشغيل 1Salem عند تسجيل الدخول إلى Windows",
            ["Settings.StartWithWindowsUnavailable"] = "يمكن للتطبيق المثبّت فقط أن يبدأ مع Windows.",
            ["Settings.StartWithWindowsFailed"] = "لم يقبل Windows إعداد بدء التشغيل.",
            ["Settings.CloseBehaviour"] = "إغلاق النافذة يُبقي 1Salem في منطقة الإشعارات. خوادمك تستمر في العمل في كلتا الحالتين؛ إغلاق النافذة لا يوقفها أبدًا.",
            ["Settings.Agent.Version"] = "إصدار الخدمة  {0}",
            ["Settings.Agent.Machine"] = "الكمبيوتر  {0}",
            ["Settings.Agent.DatabaseReady"] = "قاعدة البيانات  جاهزة",
            ["Settings.Agent.DatabaseStarting"] = "قاعدة البيانات  قيد التشغيل",
            ["Appearance.NotSaved"] = "طُبّق الآن، لكن تعذّر حفظه للمرة القادمة.",
            ["Settings.BackupsPolicy"] = "جداول النسخ الاحتياطي ومدد الاحتفاظ تخص كل خادم، لذا توجد مع ذلك الخادم. صفحة النسخ الاحتياطية تعرض الخوادم التي تحتاج انتباهك.",
            ["Settings.BackupsPolicyAction"] = "الانتقال إلى النسخ الاحتياطية",
            ["Settings.NetworkPolicy"] = "يُعدّ الوصول عن بُعد من صفحة الشبكة، التي تعرض أيضًا العنوان الذي تشاركه وما إذا كان بإمكان الآخرين الوصول إليك.",
            ["Settings.NetworkPolicyAction"] = "الانتقال إلى الشبكة",
            ["Settings.VersionValue"] = "الإصدار {0}",
            ["Settings.BuildValue"] = "البناء {0}",
            ["Settings.AdvancedIntro"] = "أدوات استكشاف الأخطاء. لا تحتاج إلى أي منها للاستخدام العادي.",
            ["Settings.OpenDataFolder"] = "فتح مجلد البيانات",
            ["Settings.OpenLogs"] = "فتح السجلات",
            ["Settings.CopyServiceInfo"] = "نسخ التفاصيل",
            ["Settings.ServiceInformation"] = "الخدمة الخلفية",
            ["Settings.Copyright"] = "حقوق النشر © 1Salem",
            ["Updates.Details"] = "تفاصيل التحديث",
            ["Updates.CurrentVersion"] = "الإصدار الحالي",
            ["Updates.LatestVersion"] = "أحدث إصدار",
            ["Updates.Status"] = "الحالة",
            ["Updates.CheckNow"] = "التحقق الآن",
            ["Updates.Download"] = "تنزيل التحديث",
            ["Updates.Install"] = "التحديث الآن",
            ["Updates.Channel"] = "قناة الإصدار",
            ["Updates.Channel.Stable"] = "مستقر",
            ["Updates.Channel.Preview"] = "معاينة",
            ["Updates.Channel.Development"] = "تطوير",
            ["Updates.AutomaticChecks"] = "التحقق من التحديثات تلقائيًا",
            ["Updates.SavePreferences"] = "حفظ",
            ["Updates.Components"] = "المكوّنات المثبّتة",
            ["Updates.Component.Client"] = "التطبيق",
            ["Updates.Component.Agent"] = "الخدمة الخلفية",
            ["Updates.Component.Updater"] = "أداة التحديث",
            ["Updates.Component.Channel"] = "القناة",
            ["Updates.ReleaseNotes"] = "ملاحظات الإصدار",
            ["Updates.History"] = "سجل التحديثات",
            ["Updates.NotChecked"] = "لم يتم التحقق",
            ["Updates.Loading"] = "جارٍ جلب حالة التحديث…",
            ["Updates.Unavailable"] = "حالة التحديث غير متاحة حاليًا.",
            ["Updates.NotCheckedYet"] = "لم يتم التحقق من حالة التحديث بعد.",
            ["Updates.UpToDate"] = "1Salem محدّث. آخر تحقق {0}.",
            ["Updates.Available"] = "يتوفر تحديث. افتح تفاصيل التحديث لتنزيله وتثبيته.",
            ["Updates.ReadyToInstall"] = "تم تنزيل التحديث والتحقق منه، وهو جاهز للتثبيت.",
            ["Updates.LastStepFailed"] = "لم تنجح آخر خطوة تحديث. حاول التحقق مرة أخرى.",
            ["Updates.GameServerBusy"] = "يعمل خادم ألعاب الآن. يمكن تحديث التطبيق الآن، وتُحدَّث الخدمة الخلفية عند إعادة تشغيلها الآمنة التالية.",
            ["Updates.LastChecked"] = "آخر تحقق: {0}",
            ["Updates.Never"] = "أبدًا",
            ["Updates.InstalledHistory"] = "آخر تحديث: {0} · السابق: {1} · التراجع: {2}",
            ["Updates.NotRecorded"] = "غير مسجّل",
            ["Updates.None"] = "لا يوجد",
            ["Updates.Signed"] = "هذا البناء موقّع رقميًا.",
            ["Updates.Unsigned"] = "هذا البناء غير موقّع رقميًا. ومع ذلك تُفحص حزم التحديث من حيث الحجم الدقيق وSHA-256 قبل التثبيت.",
            ["Updates.NoRollback"] = "لم تكن هناك حاجة إلى التراجع.",
            ["Updates.DownloadHint"] = "تنزيل التحديث المتاح والتحقق منه.",
            ["Updates.DownloadDisabledHint"] = "تحقّق من وجود تحديث أولًا.",
            ["Updates.InstallHint"] = "تثبيت التحديث الذي تم التحقق منه. يُحتفظ بالإصدار الحالي لإمكانية التراجع.",
            ["Updates.InstallDisabledHint"] = "نزّل التحديث وتحقّق منه قبل التثبيت.",
            ["Updates.PreferencesSaved"] = "تم حفظ تفضيلات التحديث.",
            ["Updates.PreferencesFailed"] = "تعذّر حفظ تفضيلات التحديث.",
            ["Updates.PrepareFailed"] = "تعذّر تجهيز التحديث للتثبيت.",
            ["Updates.LaunchFailed"] = "تعذّر تشغيل أداة التحديث.",
            ["Updates.Working"] = "جارٍ العمل…",
            ["Updates.ActionFailed"] = "لم تنجح خطوة التحديث. حاول مرة أخرى.",
            ["Updates.Stage.Idle"] = "خامل",
            ["Updates.Stage.Checking"] = "جارٍ التحقق من التحديثات…",
            ["Updates.Stage.Available"] = "يتوفر تحديث",
            ["Updates.Stage.Downloading"] = "جارٍ تنزيل التحديث…",
            ["Updates.Stage.Verified"] = "تم التنزيل والتحقق",
            ["Updates.Stage.ReadyToInstall"] = "جاهز للتثبيت",
            ["Updates.Stage.Installing"] = "جارٍ تثبيت التحديث…",
            ["Updates.Stage.Succeeded"] = "تم التحديث",
            ["Updates.Stage.Failed"] = "فشل",
            ["Updates.Stage.RolledBack"] = "تم التراجع",
            ["Updates.Stage.FullSetupRequired"] = "يتطلب المثبّت الكامل",
            ["Updates.Stage.UpdatePendingRestart"] = "يكتمل بعد إعادة التشغيل",
            ["Updates.Stage.InstalledVersionNewer"] = "الإصدار المثبّت أحدث",
            ["Updates.Stage.IncompleteComponentUpdate"] = "التحديث غير مكتمل",
            ["Backups.None"] = "لم يتم إنشاء أي نسخة احتياطية لهذا الخادم بعد.",
            ["Backups.NoneAnywhere"] = "لم يتم إنشاء أي نسخة احتياطية بعد.",
            ["Backups.ListUnavailable"] = "تعذّر عرض بعض النسخ الاحتياطية الآن. حاول مرة أخرى بعد قليل.",
            ["Backups.OpenServerName"] = "فتح النسخ الاحتياطية لـ {0}",
            ["Backups.RestoreName"] = "استعادة {0} ({1})",
            ["Backups.VerifyName"] = "التحقق من {0} ({1})",
            ["Backups.DeleteName"] = "حذف {0} ({1})",
            ["Backups.Error.Busy"] = "الخادم مشغول بعملية أخرى. حاول مرة أخرى عند انتهائها.",
            ["Backups.Error.NotFound"] = "هذه النسخة الاحتياطية لم تعد موجودة.",
            ["Backups.Error.Failed"] = "تعذّر على الخدمة الخلفية إتمام ذلك. التفاصيل في السجلات.",
            ["Confirm.RestoreBackup"] = "الاستعادة ستستبدل العالم الحالي على '{0}' بالنسخة الاحتياطية '{1}'. هل تريد المتابعة؟",
            ["Backups.Files"] = "{0} ملفًا",
            ["Backups.Protected"] = "محمية",
            ["Backups.Status.Completed"] = "مكتملة",
            ["Backups.Status.Failed"] = "فشلت",
            ["Backups.Status.Corrupt"] = "تالفة",
            ["Backups.Status.Pending"] = "قيد الانتظار",
            ["Content.Subtitle"] = "الإضافات الخاصة بهذا الخادم.",
            ["Content.MinecraftSubtitle"] = "إضافات لخادم ماينكرافت هذا، من Hangar و Modrinth.",
            ["Content.PalworldSubtitle"] = "الإضافات الخاصة بخادم بال وورلد هذا.",
            ["Content.ComingTitle"] = "لا يوجد ما يمكن تثبيته بعد",
            ["Content.ComingMessage"] = "تصفّح الإضافات وتثبيتها سيأتي في تحديث لاحق. سيستمر هذا الخادم في العمل كما هو تمامًا.",
            ["Action.Close"] = "إغلاق",
            ["Content.Discover"] = "استكشاف",
            ["Content.Installed"] = "المثبَّتة",
            ["Content.Updates"] = "التحديثات",
            ["Content.Details"] = "التفاصيل",
            ["Content.CompatibleOnly"] = "تعمل مع هذا الخادم",
            ["Content.SearchLabel"] = "ابحث عن إضافة",
            ["Content.SortLabel"] = "الترتيب",
            ["Content.ProviderLabel"] = "المصدر",
            ["Content.ResultsList"] = "نتائج الإضافات",
            ["Content.Sort.Relevance"] = "الأنسب",
            ["Content.Sort.Downloads"] = "الأكثر تنزيلًا",
            ["Content.Sort.Updated"] = "المحدَّثة حديثًا",
            ["Content.Sort.Newest"] = "الأحدث",
            ["Content.Provider.All"] = "كل المصادر",
            ["Content.Install"] = "تثبيت",
            ["Content.AlreadyInstalled"] = "مثبَّتة",
            ["Content.Update"] = "تحديث",
            ["Content.Rollback"] = "الرجوع للسابقة",
            ["Content.Uninstall"] = "إزالة",
            ["Content.ViewProject"] = "عرض المشروع",
            ["Content.ViewOn"] = "عرضها على {0}",
            ["Content.ByAuthor"] = "بواسطة {0}",
            ["Content.Source"] = "المصدر: {0}",
            ["Content.SourceUnknown"] = "المصدر: غير معروف",
            ["Content.Downloads"] = "{0} تنزيل",
            ["Content.MinecraftVersion"] = "ماينكرافت {0}",
            ["Content.Unknown"] = "غير معروف",
            ["Content.VersionUnknown"] = "الإصدار غير معروف",
            ["Content.VersionNamed"] = "الإصدار {0}",
            ["Content.UpdateFromTo"] = "{0} إلى {1}",
            ["Content.InstallNamed"] = "تثبيت {0}",
            ["Content.UpdateNamed"] = "تحديث {0}",
            ["Content.UninstallNamed"] = "إزالة {0}",
            ["Content.RestartRequired"] = "أعد تشغيل الخادم حتى يتم تحميلها.",
            ["Content.Done"] = "تم.",
            ["Content.State.UpToDate"] = "محدَّثة",
            ["Content.State.UpdateAvailable"] = "يتوفر تحديث",
            ["Content.State.RestartRequired"] = "تحتاج إعادة تشغيل",
            ["Content.State.InstalledManually"] = "أضفتها بنفسك",
            ["Content.State.MissingFile"] = "الملف مفقود",
            ["Content.State.ModifiedLocally"] = "تغيّر الملف على القرص",
            ["Content.State.UnknownVersion"] = "الإصدار غير معروف",
            ["Content.Channel.Release"] = "إصدار مستقر",
            ["Content.Channel.Beta"] = "تجريبية",
            ["Content.Channel.Alpha"] = "أولية",
            ["Content.Details.Facts"] = "التفاصيل",
            ["Content.Details.About"] = "عن هذه الإضافة",
            ["Content.Details.LatestCompatible"] = "الأحدث المناسبة",
            ["Content.Details.Platforms"] = "برنامج الخادم",
            ["Content.Details.GameVersions"] = "إصدارات ماينكرافت",
            ["Content.Details.License"] = "الترخيص",
            ["Content.Details.Dependencies"] = "تحتاج أيضًا",
            ["Content.Details.NoCompatible"] = "لا يوجد ما يناسب هذا الخادم",
            ["Content.Details.NoDependencies"] = "لا شيء آخر",
            ["Content.Loading"] = "جارٍ التحميل",
            ["Content.LoadingMessage"] = "جارٍ سؤال مواقع الإضافات.",
            ["Content.Empty.Title"] = "لم يتم العثور على إضافات",
            ["Content.Empty.Message"] = "جرّب كلمات أخرى، أو ألغِ تحديد \"تعمل مع هذا الخادم\" لعرض المزيد.",
            ["Content.NoInstalled.Title"] = "لا توجد إضافات بعد",
            ["Content.NoInstalled.Message"] = "كل ما تثبّته يظهر هنا، مع الإضافات التي أضفتها بنفسك.",
            ["Content.NoUpdates.Title"] = "كل شيء محدَّث",
            ["Content.NoUpdates.Message"] = "لا توجد تحديثات مناسبة لهذا الخادم في الانتظار.",
            ["Content.Unsupported.Title"] = "الإضافات غير متاحة هنا",
            ["Content.Unsupported.Vanilla"] = "هذا الخادم لا يدعم الإضافات. ماينكرافت الأصلي بلا نظام إضافات، بينما خوادم Paper و Purpur و Spigot و Bukkit تدعمه.",
            ["Content.Unsupported.UnknownPlatform"] = "تعذّر التعرّف على برنامج الخادم، لذلك لا تُعرض أي إضافات.",
            ["Content.Unsupported.UnknownVersion"] = "تعذّرت قراءة إصدار ماينكرافت، لذلك لا يمكن التحقق من التوافق.",
            ["Content.Unsupported.MissingRoot"] = "تعذّر العثور على مجلد الخادم.",
            ["Content.Unsupported.NotMinecraft"] = "الإضافات ميزة خاصة بماينكرافت.",
            ["Content.Stage.Downloading"] = "جارٍ التنزيل والتحقق.",
            ["Content.Stage.Removing"] = "جارٍ الإزالة.",
            ["Content.Installed.Title"] = "تم تثبيت الإضافة",
            ["Content.Installed.Message"] = "جاهزة للاستخدام.",
            ["Content.Install.FailedTitle"] = "تعذّر التثبيت",
            ["Content.Install.BlockedTitle"] = "لم يتم تثبيت أي شيء",
            ["Content.Updated.Title"] = "تم تحديث الإضافة",
            ["Content.Update.FailedTitle"] = "تعذّر التحديث",
            ["Content.RolledBack.Title"] = "تمت استعادة النسخة السابقة",
            ["Content.Rollback.FailedTitle"] = "تعذّر الرجوع",
            ["Content.Uninstalled.Title"] = "تمت إزالة الإضافة",
            ["Content.Uninstall.FailedTitle"] = "تعذّرت الإزالة",
            ["Content.Dependencies.Title"] = "تثبيت إضافة",
            ["Content.Dependencies.Heading"] = "{0} تحتاج إضافات أخرى",
            ["Content.Dependencies.Body"] = "سيتم تثبيت هذه أيضًا، لأن الإضافة لن تعمل بدونها.",
            ["Content.Dependencies.Confirm"] = "تثبيت الكل",
            ["Content.Uninstall.Title"] = "إزالة إضافة",
            ["Content.Uninstall.Heading"] = "إزالة {0}؟",
            ["Content.Uninstall.Body"] = "سيُحذف ملف الإضافة من هذا الخادم. أما مجلد إعداداتها فيبقى، لذلك تعود إعداداتك إذا ثبّتها مرة أخرى.",
            ["Content.Uninstall.Confirm"] = "إزالة الإضافة",
            ["Content.Error.AgentTitle"] = "تعذّر الوصول إلى الخدمة الخلفية",
            ["Content.Error.AgentMessage"] = "تعذّر على مدير خوادم 1Salem الوصول إلى خدمته الخلفية.",
            ["Content.Error.ProvidersTitle"] = "مواقع الإضافات غير متاحة",
            ["Content.Error.ProvidersMessage"] = "تعذّر الوصول إلى Hangar و Modrinth الآن. حاول بعد قليل.",
            ["Content.Error.Offline"] = "لا يوجد اتصال بالإنترنت.",
            ["Content.Error.RateLimited"] = "طلب منا موقع الإضافات التمهّل. حاول بعد قليل.",
            ["Content.Error.ApiRetired"] = "غيّر موقع الإضافات طريقة عمله. حدّث مدير خوادم 1Salem.",
            ["Content.Error.HashMismatch"] = "لم يطابق الملف المنزَّل بصمة الموقع نفسه، لذلك تم التخلص منه.",
            ["Content.Error.InvalidJar"] = "الملف المنزَّل ليس ملف إضافة صالحًا.",
            ["Content.Error.ServerBusy"] = "الخادم مشغول بمهمة أخرى. حاول عند انتهائها.",
            ["Content.Error.FileInUse"] = "الخادم يستخدم هذا الملف. أوقف الخادم ثم حاول مرة أخرى.",
            ["Content.Error.AccessDenied"] = "رفض ويندوز الوصول إلى مجلد الإضافات.",
            ["Content.Error.NoCompatibleVersion"] = "لا يوجد إصدار يناسب إصدار ماينكرافت في هذا الخادم.",
            ["Content.Error.NoRollback"] = "لا توجد نسخة سابقة محفوظة للرجوع إليها.",
            ["Content.Error.AlreadyCurrent"] = "هذه الإضافة محدَّثة بالفعل.",
            ["Content.Error.DependencyIncompatible"] = "إحدى الإضافات المطلوبة ليس لها إصدار يناسب هذا الخادم، لذلك لم يتم تثبيت شيء.",
            ["Content.Error.DependencyUnresolvable"] = "تعذّر العثور تلقائيًا على إحدى الإضافات المطلوبة، لذلك لم يتم تثبيت شيء.",
            ["Content.Error.Generic"] = "لم تنجح العملية. لم يتغيّر شيء.",
            ["Content.Error.LinkTitle"] = "تعذّر فتح الرابط",
            ["Content.Error.LinkMessage"] = "تعذّر فتح المتصفح.",
            ["Content.KindLabel"] = "النوع",
            ["Content.Kind.Plugin"] = "إضافة",
            ["Content.Kind.Modpack"] = "حزمة تعديلات",
            ["Content.Kind.DataPack"] = "حزمة بيانات",
            ["Content.Kind.ResourcePack"] = "حزمة موارد",
            ["Content.CreateServer"] = "إنشاء خادم",
            ["Content.CreateServerNamed"] = "إنشاء خادم من {0}",
            ["Content.Distribute"] = "استخدامها في هذا الخادم",
            ["Content.DistributeNamed"] = "إرسال {0} للاعبين المنضمين لهذا الخادم",
            ["Content.Withdraw"] = "إيقاف الإرسال",
            ["Content.State.ReloadRequired"] = "تحتاج إعادة تحميل",
            ["Content.State.Incompatible"] = "مصنوعة لإصدار آخر",
            ["Content.State.NotDistributed"] = "تم تنزيلها",
            ["Content.State.Distributed"] = "تُرسل للاعبين",
            ["Content.State.RequiresMigration"] = "يتطلب ترحيل الخادم",
            ["Content.MigrationNeeded"] = "الإصدار {0} يحتاج إصدار ماينكرافت أو مُحمّلًا مختلفًا، لذلك لا يمكن تطبيقه كتحديث.",
            ["Content.Distributed.Title"] = "ستُعرض هذه الحزمة على اللاعبين",
            ["Content.Distributed.Message"] = "سيحصلون عليها عند الاتصال القادم.",
            ["Content.Distribute.FailedTitle"] = "تعذّر تغيير حزمة الموارد",
            ["Content.Withdrawn.Title"] = "لن تُعرض أي حزمة على اللاعبين بعد الآن",
            ["Content.Stage.ResolvingPack"] = "جارٍ قراءة الحزمة.",
            ["Content.Stage.BuildingServer"] = "جارٍ بناء الخادم الجديد.",
            ["Content.Modpack.Title"] = "إنشاء خادم من حزمة تعديلات",
            ["Content.Modpack.Subtitle"] = "حزمة التعديلات تحدد إصدار ماينكرافت والمُحمّل وكل التعديلات، لذلك تُنشئ دائمًا خادمًا جديدًا. لن يتغيّر أي شيء في خوادمك الحالية.",
            ["Content.Modpack.Loader"] = "مُحمّل التعديلات",
            ["Content.Modpack.PackVersion"] = "إصدار الحزمة",
            ["Content.Modpack.Size"] = "التنزيل",
            ["Content.Modpack.SizeValue"] = "{0} ملف، نحو {1}",
            ["Content.Modpack.ServerName"] = "اسم الخادم",
            ["Content.Modpack.Location"] = "مكان الحفظ",
            ["Content.Modpack.Port"] = "المنفذ",
            ["Content.Modpack.Browse"] = "استعراض",
            ["Content.Modpack.Eula"] = "أوافق على اتفاقية ترخيص المستخدم لماينكرافت",
            ["Content.Modpack.Create"] = "إنشاء الخادم",
            ["Content.Modpack.NeedName"] = "أعطِ الخادم اسمًا.",
            ["Content.Modpack.NeedLocation"] = "اختر مجلدًا للخادم.",
            ["Content.Modpack.NeedPort"] = "أدخل منفذًا بين 1 و 65535.",
            ["Content.Modpack.NeedEula"] = "يجب قبول ترخيص ماينكرافت قبل تشغيل أي خادم.",
            ["Content.Modpack.FolderNotEmpty"] = "هذا المجلد يحتوي على ملفات بالفعل. اختر مجلدًا فارغًا أو جديدًا.",
            ["Content.Modpack.LoaderUnsupported"] = "تحتاج هذه الحزمة مُحمّل {0}، وله برنامج تثبيت خاص به. مدير خوادم 1Salem لا يشغّل برامج تثبيت أخرى، لذلك لا يمكن إعداد هذه الحزمة هنا بعد. حزم Fabric تعمل.",
            ["Content.Modpack.UnsafePack"] = "تطلب هذه الحزمة كتابة ملفات خارج مجلد الخادم، أو من موقع لا يسمح به المزوّد. لم يتم تنزيل أي شيء.",
            ["Content.Modpack.UnreadablePack"] = "تعذّرت قراءة فهرس هذه الحزمة، لذلك لم يتم تنزيل أي شيء.",
            ["Content.Modpack.TooLarge"] = "هذه الحزمة أكبر مما سيُنزّله التطبيق دفعة واحدة.",
            ["Content.Modpack.CreatedTitle"] = "تم إنشاء الخادم",
            ["Content.Modpack.CreatedMessage"] = "{0} جاهز على ماينكرافت {1}. شغّله من صفحة الخوادم.",
            ["Content.Modpack.FailedTitle"] = "تعذّر إنشاء الخادم",
            ["Content.Error.NeedsReachableUrl"] = "يحتاج اللاعبون إلى عنوان ويب للحزمة، وهذه ليس لها عنوان. هذا التطبيق لا يستضيف ملفات ولا يفتح منافذ.",
            ["Content.Error.NoSha1"] = "لم ينشر المزوّد البصمة التي يحتاجها ماينكرافت لهذا.",
            ["Content.Error.PackTooLarge"] = "يرفض ماينكرافت حزم موارد الخادم الأكبر من 250 ميبي بايت.",
            ["Content.Error.NoWorld"] = "تعذّر تحديد عالم الخادم من إعداداته، لذلك لا يوجد مكان آمن لوضع هذا.",
            ["Content.Error.InvalidArchive"] = "الملف المنزَّل ليس حزمة صالحة.",
            ["Content.Error.DestinationNotEmpty"] = "هذا المجلد يحتوي على ملفات بالفعل.",
            ["Content.Error.EulaRequired"] = "يجب قبول ترخيص ماينكرافت أولًا.",
            ["Content.Error.JavaMissing"] = "لم يتم العثور على نسخة جافا مناسبة لهذه الحزمة.",
            ["Content.Error.FileUnavailable"] = "تعذّر تنزيل أحد الملفات التي تحتاجها الحزمة أو لم يطابق بصمته. لم يتم الاحتفاظ بشيء.",
            ["Content.Error.UnsupportedServer"] = "هذا الخادم لا يقبل هذا النوع من المحتوى.",
            ["Content.Error.PortInUse"] = "يوجد خادم آخر على هذا الجهاز معدّ بالفعل على هذا المنفذ. اختر منفذًا مختلفًا.",
            ["Content.Error.RegistrationFailed"] = "تعذّر تسجيل الخادم الجديد، لذلك لم يتم الاحتفاظ بشيء.",
            ["ServerSettings.General"] = "عام",
            ["ServerSettings.Game"] = "اللعبة",
            ["ServerSettings.Network"] = "الشبكة",
            ["ServerSettings.Resources"] = "الموارد",
            ["ServerSettings.Advanced"] = "متقدم",
            ["ServerSettings.AutoStart"] = "تشغيل هذا الخادم عند بدء تشغيل الجهاز",
            ["ServerSettings.AutoRestart"] = "إعادة التشغيل تلقائيًا إذا توقف بشكل غير متوقع",
            ["ServerSettings.Updates"] = "تحديثات الخادم",
            ["ServerSettings.UpdatesUnknown"] = "لم يتم التحقق من حالة التحديث بعد.",
            ["ServerSettings.UpToDate"] = "هذا الخادم محدَّث.",
            ["ServerSettings.UpdateAvailable"] = "الإصدار {0} متاح.",
            ["ServerSettings.GameBody"] = "خيارات العالم وطريقة اللعب لهذا الخادم.",
            ["ServerSettings.NetworkBody"] = "كيف يصل اللاعبون إلى هذا الخادم، والعنوان الذي تشاركه معهم.",
            ["ServerSettings.ResourcesBody"] = "حدود الذاكرة والمعالج. تنطبق هذه الإعدادات على كل الخوادم على هذا الكمبيوتر، وليس على هذا الخادم وحده.",
            ["ServerSettings.AdvancedIntro"] = "معلومات تقنية لاستكشاف الأخطاء. لا تحتاج إلى أي منها للاستخدام العادي.",
            ["Advanced.Threads"] = "مؤشرات الترابط",
            ["Advanced.Management"] = "الإدارة المحلية",
            ["Advanced.RestPort"] = "منفذ الإدارة",
            ["Advanced.Connected"] = "متصل",
            ["Advanced.Disconnected"] = "غير متصل",
            ["Advanced.PortOpen"] = "مفتوح",
            ["Advanced.PortClosed"] = "مغلق",
            ["Error.ActionFailed"] = "لم ينجح ذلك",
            ["Error.FolderUnavailable"] = "تعذّر العثور على مجلد هذا الخادم.",
            ["Advanced.RootProcess"] = "العملية الجذر",
            ["Advanced.GameProcess"] = "عملية اللعبة",
            ["Advanced.ChildProcesses"] = "العمليات الفرعية",
            ["Advanced.Port"] = "المنفذ",
            ["Appearance.Title"] = "اللغة والمظهر",
            ["Appearance.Description"] = "تُطبَّق التغييرات فورًا وتُحفظ للتشغيل التالي.",
            ["Appearance.Language"] = "اللغة",
            ["Appearance.Theme"] = "المظهر",
            ["Appearance.English"] = "English",
            ["Appearance.Arabic"] = "العربية",
            ["Appearance.Dark"] = "داكن",
            ["Appearance.Light"] = "فاتح",
            ["Appearance.FollowWindows"] = "اتباع إعداد Windows",
            ["Appearance.Apply"] = "تطبيق",
            ["Appearance.Applied"] = "تم تطبيق اللغة والمظهر.",
            ["Appearance.ScopeDescription"] = "مظهر لوحة التحكم منفصل عن إعدادات البدء وإعادة التشغيل التلقائي لكل خادم.",
            ["Shell.Navigation"] = "☰ التنقل",
            ["Shell.ShowNavigation"] = "☰ إظهار التنقل",
            ["Shell.HideNavigation"] = "☰ إخفاء التنقل",
            ["Shell.AdministratorTools"] = "أدوات المسؤول",
            ["Shell.AdministratorMode"] = "وضع المسؤول",
            ["Shell.NormalMode"] = "الوضع العادي",
            ["Shell.Connected"] = "متصل",
            ["Shell.AgentUnavailable"] = "غير متصل",
            ["Shell.Connecting"] = "جارٍ الاتصال…",
            ["Shell.Footer"] = "يتم تحديث حالة الخادم تلقائيًا",
            ["Shell.Dismiss"] = "إغلاق",
            ["Palworld.Overview.Title"] = "نظرة عامة مباشرة على الخادم",
            ["Palworld.Overview.Loading"] = "جارٍ التحميل…",
            ["Palworld.Overview.LoadingLiveData"] = "جارٍ تحميل بيانات الخادم المباشرة",
            ["Palworld.Overview.Unavailable"] = "غير متاح",
            ["Palworld.Overview.Stale"] = "بيانات قديمة",
            ["Palworld.Overview.ServerStopped"] = "الخادم متوقف",
            ["Palworld.Overview.RuntimeUnavailable"] = "بيئة التشغيل غير متاحة",
            ["Palworld.Overview.LivePlayers"] = "عدد اللاعبين المباشر",
            ["Palworld.Overview.LiveRestMetric"] = "مقياس REST مباشر",
            ["Palworld.Overview.ProcessUptime"] = "مدة تشغيل العملية",
            ["Palworld.Overview.LogicalProcessors"] = "{0} معالجات منطقية",
            ["Palworld.Overview.WarningAt"] = "تحذير عند {0}",
            ["Palworld.Overview.WorkingSet"] = "ذاكرة العملية المستخدمة",
            ["Palworld.Overview.NoBackup"] = "لا توجد نسخة احتياطية مسجلة",
            ["Palworld.Overview.PercentOfWarning"] = "{0:0}% من حد التحذير {1}",
            ["Palworld.Overview.WarningUnavailable"] = "حد تحذير الذاكرة غير متاح",
            ["Palworld.Overview.DiskFree"] = "{0} متاح",
            ["Palworld.Overview.DaysAgo"] = "منذ {0} يوم",
            ["Palworld.Overview.HoursAgo"] = "منذ {0} ساعة",
            ["Palworld.Overview.MinutesAgo"] = "منذ {0} دقيقة",
            ["Palworld.Overview.Status"] = "الحالة",
            ["Palworld.Overview.QuickActions"] = "إجراءات سريعة",
            ["Palworld.Overview.ServerActivity"] = "نشاط الخادم",
            ["Palworld.Overview.RecentActivity"] = "النشاط الأخير",
            ["Palworld.Overview.ResourceSummary"] = "ملخص الموارد",
            ["Palworld.Overview.Connections"] = "الاتصالات",
            ["Palworld.Overview.LocalNetwork"] = "الشبكة المحلية",
            ["Palworld.Overview.InternetPlayit"] = "الإنترنت / Playit",
            ["Palworld.Overview.NoHistory"] = "سيظهر السجل عند وصول العينات المباشرة.",
            ["Palworld.Overview.NoActivity"] = "لا يوجد نشاط حديث للخادم.",
            ["Palworld.Overview.TimeRange"] = "النطاق الزمني",
            ["Palworld.Overview.Badge.ProcessRunning"] = "العملية تعمل",
            ["Palworld.Overview.Badge.PortOpen"] = "المنفذ مفتوح",
            ["Palworld.Overview.Badge.GameReady"] = "اللعبة جاهزة",
            ["Palworld.Overview.Badge.RestConnected"] = "REST متصل",
            ["Palworld.Overview.Badge.PlayitOnline"] = "Playit متصل",
            ["Palworld.Overview.Badge.PublicMappingValid"] = "التوجيه العام صالح",
            ["Palworld.Overview.Metric.Players"] = "اللاعبون",
            ["Palworld.Overview.Metric.Fps"] = "إطارات الخادم",
            ["Palworld.Overview.Metric.Uptime"] = "مدة التشغيل",
            ["Palworld.Overview.Metric.Cpu"] = "المعالج",
            ["Palworld.Overview.Metric.Ram"] = "الذاكرة",
            ["Palworld.Overview.Metric.LastBackup"] = "آخر نسخة",
            ["Palworld.Overview.Action.Start"] = "تشغيل الخادم",
            ["Palworld.Overview.Action.Refresh"] = "تحديث",
            ["Palworld.Overview.Action.SaveWorld"] = "حفظ العالم",
            ["Palworld.Overview.Action.Announcement"] = "إعلان",
            ["Palworld.Overview.Action.GracefulStop"] = "إيقاف آمن",
            ["Palworld.Overview.Action.Restart"] = "إعادة التشغيل",
            ["Palworld.Overview.Action.BackupNow"] = "نسخ احتياطي الآن",
            ["Palworld.Overview.Action.CopyInternet"] = "نسخ عنوان الإنترنت",
            ["Palworld.Overview.Action.Copy"] = "نسخ",
            ["Palworld.Overview.Action.Send"] = "إرسال",
            ["Palworld.Overview.Action.Cancel"] = "إلغاء",
            ["Palworld.Overview.AnnouncementHint"] = "رسالة للاعبين المتصلين",
            ["Palworld.Overview.Resource.Cpu"] = "استخدام المعالج",
            ["Palworld.Overview.Resource.Ram"] = "استخدام الذاكرة",
            ["Palworld.Overview.Resource.Disk"] = "استخدام القرص",
            ["Palworld.Overview.Activity.Source"] = "المصدر: {0}",
            ["Palworld.Overview.Activity.Succeeded"] = "اكتمل",
            ["Palworld.Overview.Activity.Failed"] = "فشل"
        };

    /// <summary>
    /// Raised after the language changes. Views that resolve their text in code rather than
    /// through a DynamicResource must re-read it here; without this they keep whatever
    /// language they happened to be built in, including the Settings page the switch was
    /// made on.
    /// </summary>
    public static event EventHandler? LanguageChanged;

    public static string Get(string key) => Table.TryGetValue(key, out var value) ? value : key;

    /// <summary>
    /// Whether the current language actually defines this key. <see cref="Get"/> echoes the
    /// key back when it is missing, which is indistinguishable from a legitimate value for
    /// entries such as "Minecraft", so callers that need certainty ask here.
    /// </summary>
    public static bool HasKey(string key) => Table.ContainsKey(key);

    private static IReadOnlyDictionary<string, string> Table =>
        CultureInfo.CurrentUICulture.TextInfo.IsRightToLeft ? Arabic : English;

    /// <summary>
    /// Formats a localized template. Sentences are built from a single template with
    /// placeholders rather than concatenated fragments, because fragment order is not
    /// preserved across languages.
    /// </summary>
    public static string Format(string key, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentUICulture, Get(key), arguments);

    public static void Apply(string language)
    {
        var culture = CultureInfo.GetCultureInfo(language);
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        var application = System.Windows.Application.Current;
        if (application is not null)
        {
            foreach (var key in English.Keys)
            {
                application.Resources[key] = Get(key);
            }
        }

        LanguageChanged?.Invoke(null, EventArgs.Empty);
    }
}
